#include <stdio.h>
#include <sys/ioctl.h>

#include "maplesyrup.h"
#include "parse.h"
#include "parse_breakout.h"
#include "bitfield_armv7a.h"


bitfield_info bitfield_armv7a_table[] =
{       
    /* Identification Bitfields */ 
    { BO_V7A_PFR0_STATE0, MS_IOCTL_PFR0, NS_PRIVILEGE_LEVEL_1, 0, 4, "State0", "ident", "PFR0", "ARM instruction set support" },
    { BO_V7A_PFR0_STATE1, MS_IOCTL_PFR0, NS_PRIVILEGE_LEVEL_1, 4, 4, "State1", "ident", "PFR0", "Thumb instruction set support" },
    { BO_V7A_PFR0_STATE2, MS_IOCTL_PFR0, NS_PRIVILEGE_LEVEL_1, 8, 4, "State2", "ident", "PFR0", "Jazelle extension support" },
    { BO_V7A_PFR0_STATE3, MS_IOCTL_PFR0, NS_PRIVILEGE_LEVEL_1, 12, 4, "State3", "ident", "PFR0", "ThumbEE instruction set support" },
    { BO_V7A_PFR0_RESERVED, MS_IOCTL_PFR0, NS_PRIVILEGE_LEVEL_1, 16, 16, "Reserved", "ident", "PFR0", "Reserved" },
    
    { BO_V7A_PFR1_PROGMODEL, MS_IOCTL_PFR1, NS_PRIVILEGE_LEVEL_1, 0, 4, "Programmers' model", "ident", "PFR1", "Programmers' model" },
    { BO_V7A_PFR1_SECEXT, MS_IOCTL_PFR1, NS_PRIVILEGE_LEVEL_1, 4, 4, "Security", "ident", "PFR1", "Security support" },
    { BO_V7A_PFR1_MMODEL, MS_IOCTL_PFR1, NS_PRIVILEGE_LEVEL_1, 8, 4, "M profile programmers' model", "ident", "PFR1", "M profile programmers' model" },
    { BO_V7A_PFR1_VIRTEXT, MS_IOCTL_PFR1, NS_PRIVILEGE_LEVEL_1, 12, 4, "Virtualization Extensions", "ident", "PFR1", "Virtualization Extensions" },
    { BO_V7A_PFR1_TIMER, MS_IOCTL_PFR1, NS_PRIVILEGE_LEVEL_1, 16, 4, "Generic Timer Extension", "ident", "PFR1", "Generic Timer Extension" },  
    { BO_V7A_PFR1_RESERVED, MS_IOCTL_PFR1, NS_PRIVILEGE_LEVEL_1, 20, 12, "Reserved", "ident", "PFR1", "Reserved" },    
    
    { BO_V7A_DFR0_CODEBUGMODEL, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 0, 4, "Coprocessor debug model", "ident", "DFR0", "Coprocessor debug model" },
    { BO_V7A_DFR0_COSECDEBUGMODEL, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 4, 4, "Coprocessor secure debug model", "ident", "DFR0", "Coprocessor secure debug model" },
    { BO_V7A_DFR0_MEMMAPDEBUGMODEL, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 8, 4, "Memory-mapped debug model", "ident", "DFR0", " Memory-mapped debug model" },
    { BO_V7A_DFR0_COTRACEMODEL, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 12, 4, "Coprocessor trace model", "ident", "DFR0", " Coprocessor trace model" },
    { BO_V7A_DFR0_MMTRACEMODEL, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 16, 4, "Memory-mapped trace model", "ident", "DFR0", "Memory-mapped trace model" },
    { BO_V7A_DFR0_MDEBUGMODEL, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 20, 4, "Debug model, M profile", "ident", "DFR0", "Debug model, M profile" },
    { BO_V7A_DFR0_PERFMONEXT, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 24, 4, "Performance Monitors Extension", "ident", "DFR0", "Performance Monitors Extension" },
    { BO_V7A_DFR0_RESERVED, MS_IOCTL_DFR0, NS_PRIVILEGE_LEVEL_1, 28, 4, "Reserved", "ident", "DFR0", "Reserved" },
    
    { BO_V7A_AFR0_IMPLEMENTATION_01, MS_IOCTL_AFR0, NS_PRIVILEGE_LEVEL_1, 0, 4, "Implementation Defined", "ident", "AFR0", "Implementation Defined" },
    { BO_V7A_AFR0_IMPLEMENTATION_02, MS_IOCTL_AFR0, NS_PRIVILEGE_LEVEL_1, 4, 4, "Implementation Defined", "ident", "AFR0", "Implementation Defined" },
    { BO_V7A_AFR0_IMPLEMENTATION_03, MS_IOCTL_AFR0, NS_PRIVILEGE_LEVEL_1, 8, 4, "Implementation Defined", "ident", "AFR0", "Implementation Defined" },
    { BO_V7A_AFR0_IMPLEMENTATION_04, MS_IOCTL_AFR0, NS_PRIVILEGE_LEVEL_1, 12, 4, "Implementation Defined", "ident", "AFR0", "Implementation Defined" },
    { BO_V7A_AFR0_RESERVED, MS_IOCTL_AFR0, NS_PRIVILEGE_LEVEL_1, 16, 16, "Reserved", "ident", "AFR0", "Reserved" },
        
    { BO_V7A_MMFR0_VMSA, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 0, 4, "VMSA support", "ident", "MMFR0", "VMSA Support" },
    { BO_V7A_MMFR0_PMSA, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 4, 4, "PMSA support", "ident", "MMFR0", "PMSA Support" },
    { BO_V7A_MMFR0_OUTSHARE, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 8, 4, "Outermost shareability", "ident", "MMFR0", "Outermost shareability" },
    { BO_V7A_MMFR0_SHARE, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 12, 4, "Shareability levels", "ident", "MMFR0", "Shareability levels" },
    { BO_V7A_MMFR0_TCM, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 16, 4, "TCM support", "ident", "MMFR0", "TCM/DMA Support" },
    { BO_V7A_MMFR0_AUX, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 20, 4, "Auxiliary registers", "ident", "MMFR0", "Auxiliary registers" },
    { BO_V7A_MMFR0_FCSE, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 24, 4, "FCSE support", "ident", "MMFR0", "FCSE support" },
    { BO_V7A_MMFR0_INSHARE, MS_IOCTL_MMFR0, NS_PRIVILEGE_LEVEL_1, 28, 4, "Innermost shareability", "ident", "MMFR0", "Innermost shareability" },
    
    { BO_V7A_MMFR1_L1HCVA, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 0, 4, "L1 Harvard cache VA", "ident", "MMFR1", "L1 Harvard cache VA" },
    { BO_V7A_MMFR1_L1UCVA, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 4, 4, "L1 unified cache VA", "ident", "MMFR1", "L1 unified cache VA" },
    { BO_V7A_MMFR1_L1HCSW, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 8, 4, "L1 Harvard cache set/way", "ident", "MMFR1", "Harvard cache set/way" },
    { BO_V7A_MMFR1_L1UCSW, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 12, 4, "L1 unified cache set/way", "ident", "MMFR1", "L1 unified cache set/way" },
    { BO_V7A_MMFR1_L1HC, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 16, 4, "L1 Harvard cache", "ident", "MMFR1", "L1 Harvard cache" },
    { BO_V7A_MMFR1_L1UC, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 20, 4, "L1 unified cache VA", "ident", "MMFR1", "L1 unified cache" },
    { BO_V7A_MMFR1_L1CTAC, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 24, 4, "L1 cache test and clean", "ident", "MMFR1", "L1 cache test and clean" },
    { BO_V7A_MMFR1_BP, MS_IOCTL_MMFR1, NS_PRIVILEGE_LEVEL_1, 28, 4, "Branch predictor", "ident", "MMFR1", "Branch predictor" },
    
    { BO_V7A_MMFR2_L1HFGF, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 0, 4, "L1 Harvard fg fetch", "ident", "MMFR2", "L1 Harvard fg fetch" },
    { BO_V7A_MMFR2_L1HBGF, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 4, 4, "L1 Harvard bg fetch", "ident", "MMFR2", "L1 Harvard bg fetch" },
    { BO_V7A_MMFR2_L1HR, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 8, 4, "L1 Harvard range", "ident", "MMFR2", "L1 Harvard range" },
    { BO_V7A_MMFR2_HTLB, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 12, 4, "Harvard TLB", "ident", "MMFR2", "Harvard TLB" },
    { BO_V7A_MMFR2_UTLB, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 16, 4, "Unified TLB", "ident", "MMFR2", "Unified TLB" },
    { BO_V7A_MMFR2_MEMBAR, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 20, 4, "Mem barrier", "ident", "MMFR2", "Mem barrier" },
    { BO_V7A_MMFR2_WFI, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 24, 4, "WFI stall", "ident", "MMFR2", "WFI stall" },
    { BO_V7A_MMFR2_HWACCESS, MS_IOCTL_MMFR2, NS_PRIVILEGE_LEVEL_1, 28, 4, "HW Access flag", "ident", "MMFR2", "HW Access flag" },
    
    { BO_V7A_MMFR3_CMMVA, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 0, 4, "Cache maintain MVA", "ident", "MMFR3", "Cache maintain MVA" },
    { BO_V7A_MMFR3_CMSW, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 4, 4, "Cache maintain set/way", "ident", "MMFR3", "Cache maintain set/way" },
    { BO_V7A_MMFR3_BPM, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 8, 4, "BP maintain", "ident", "MMFR3", "BP maintain" },
    { BO_V7A_MMFR3_MB, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 12, 4, "Maintenance broadcast", "ident", "MMFR3", "Maintenance broadcast" },
    { BO_V7A_MMFR3_RESERVED, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 16, 4, "Reserved", "ident", "MMFR3", "Reserved" },
    { BO_V7A_MMFR3_CW, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 20, 4, "Coherent walk", "ident", "MMFR3", "Coherent walk" },
    { BO_V7A_MMFR3_CMS, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 24, 4, "Cached memory size", "ident", "MMFR3", "Cached memory size" },
    { BO_V7A_MMFR3_SS, MS_IOCTL_MMFR3, NS_PRIVILEGE_LEVEL_1, 28, 4, "Supersection support", "ident", "MMFR3", "Supersection support" },
        
    { BO_V7A_ISAR0_SWAP, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 0, 4, "Swap_instrs", "ident", "ISAR0", "Swap_instrs" },
    { BO_V7A_ISAR0_BITCOUNT, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 4, 4, "BitCount_instrs", "ident", "ISAR0", "BitCount_instrs" },
    { BO_V7A_ISAR0_BITFIELD, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 8, 4, "Bitfield_instrs", "ident", "ISAR0", "Bitfield_instrs" },
    { BO_V7A_ISAR0_CMPBRANCH, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 12, 4, "CmpBranch_instrs", "ident", "ISAR0", "Compare and Branch instructions" },
    { BO_V7A_ISAR0_COPROC, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 16, 4, "Coproc_instrs", "ident", "ISAR0", "Coprocessor instructions" },
    { BO_V7A_ISAR0_DEBUG, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 20, 4, "Debug_instrs", "ident", "ISAR0", "Debug instructions" },
    { BO_V7A_ISAR0_DIVIDE, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 24, 4, "Divide_instrs", "ident", "ISAR0", "Divide instructions" },
    { BO_V7A_ISAR0_RESERVED, MS_IOCTL_ISAR0, NS_PRIVILEGE_LEVEL_1, 28, 4, "Reserved", "ident", "ISAR0", "Reserved" },
    
    { BO_V7A_ISAR1_ENDIAN, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 0, 4, "Ending_instrs", "ident", "ISAR1", "Endian instructions" },
    { BO_V7A_ISAR1_EXCEPT, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 4, 4, "Except_instrs", "ident", "ISAR1", "Exception-handling instructions" },
    { BO_V7A_ISAR1_EXCEPTAR, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 8, 4, "Except_AR_instrs", "ident", "ISAR1", "A & R profile exception-handling instructions" },
    { BO_V7A_ISAR1_EXTEND, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 12, 4, "Extend_instrs", "ident", "ISAR1", "Extend instructions" },
    { BO_V7A_ISAR1_IFTHEN, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 16, 4, "IfThen_instrs", "ident", "ISAR1", "If-Then instructions in Thumb" },
    { BO_V7A_ISAR1_IMM, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 20, 4, "Immediate_instrs", "ident", "ISAR1", "Data processing instructions on long immediates" },
    { BO_V7A_ISAR1_INTER, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 24, 4, "Interwork_instrs", "ident", "ISAR1", "Interworking instructions" },
    { BO_V7A_ISAR1_JAZELLE, MS_IOCTL_ISAR1, NS_PRIVILEGE_LEVEL_1, 28, 4, "Jazelle_instrs", "ident", "ISAR1", "Jazelle extension instructions" },
        
    { BO_V7A_ISAR2_LOADSTORE, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 0, 4, "LoadStore_instrs", "ident", "ISAR2", "Additional load/store instructions" },
    { BO_V7A_ISAR2_MEMHINT, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 4, 4, "MemHint_instrs", "ident", "ISAR2", "Memory Hint instructions" },
    { BO_V7A_ISAR2_MULTIACCESS, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 8, 4, "MultiAccessInt_instrs", "ident", "ISAR2", "Interruptible multi-access instructions" },
    { BO_V7A_ISAR2_MULTINSTRS, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 12, 4, "Mult_instrs", "ident", "ISAR2", "Additional multiply instructions" },
    { BO_V7A_ISAR2_MULTSINSTRS, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 16, 4, "MultS_instrs", "ident", "ISAR2", "Advanced signed Multiply instructions" },
    { BO_V7A_ISAR2_MULTUINSTRS, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 20, 4, "MultU_instrs", "ident", "ISAR2", "Advanced unsigned Multiply instructions" },
    { BO_V7A_ISAR2_PSRAR, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 24, 4, "PSR_AR_instrs", "ident", "ISAR2", "Instructions to manipulate PSR" },
    { BO_V7A_ISAR2_REVERSAL, MS_IOCTL_ISAR2, NS_PRIVILEGE_LEVEL_1, 28, 4, "Reversal_instrs", "ident", "ISAR2", "Implemented Reversal instructions" },
    
    { BO_V7A_ISAR3_SATURATE, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 0, 4, "Saturate_instrs", "ident", "ISAR3", "Implemented Saturate instructions" },
    { BO_V7A_ISAR3_SIMD, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 4, 4, "SIMD_instrs", "ident", "ISAR3", "Implemented SIMD instructions" },
    { BO_V7A_ISAR3_SVC, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 8, 4, "SVC_instrs", "ident", "ISAR3", "Implemented SVC instructions" },
    { BO_V7A_ISAR3_SYNCHPRIM, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 12, 4, "SynchPrim_instrs", "ident", "ISAR3", " Synchronization Primitive instructions" },
    { BO_V7A_ISAR3_TABBRANCH, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 16, 4, "TabBranch_instrs", "ident", "ISAR3", "Table Branch instructions in Thumb" },
    { BO_V7A_ISAR3_THUMBCOPY, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 20, 4, "ThumbCopy_instrs", "ident", "ISAR3", "Thumb non-flag setting MOV instructions" },
    { BO_V7A_ISAR3_TRUENOP, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 24, 4, "TrueNOP_instrs", "ident", "ISAR3", "Implemented True NOP instructions" },
    { BO_V7A_ISAR3_THUMBEE, MS_IOCTL_ISAR3, NS_PRIVILEGE_LEVEL_1, 28, 4, "ThumbEE_extn_instrs", "ident", "ISAR3", "Thumb Execution Environment Extension instructions" },
    
    { BO_V7A_ISAR4_UNPRIV, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 0, 4, "Unpriv_instrs", "ident", "ISAR4", "Implemented Unprivileged instructions" },
    { BO_V7A_ISAR4_WITHSHIFTS, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 4, 4, "WithShifts_instrs", "ident", "ISAR4", "Support for instructions with shifts" },
    { BO_V7A_ISAR4_WRITEBACK, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 8, 4, "Writeback_instrs", "ident", "ISAR4", "Writeback addressing modes" },
    { BO_V7A_ISAR4_SMC, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 12, 4, "SMC_instrs", "ident", "ISAR4", "SMC instructions" },
    { BO_V7A_ISAR4_BARRIER, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 16, 4, "Barrier_instrs", "ident", "ISAR4", "Barrier instructions" },
    { BO_V7A_ISAR4_SYNCHPRIM, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 20, 4, "SynchPrim_instrs", "ident", "ISAR4", "Implemented Synchronization Primitive instructions" },
    { BO_V7A_ISAR4_PSRM, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 24, 4, "PSR_M_instrs", "ident", "ISAR4", "M profile instructions to modify PSR" },
    { BO_V7A_ISAR4_SWP, MS_IOCTL_ISAR4, NS_PRIVILEGE_LEVEL_1, 28, 4, "SWP_frac", "ident", "ISAR4", "Bus locking on SWP or SWPB" },
    
    { BO_V7A_ISAR5_RESERVED, MS_IOCTL_ISAR5, NS_PRIVILEGE_LEVEL_1, 0, 32, "Reserved", "ident", "ISAR5", "Reserved" },
    
    { BO_V7A_REVIDR_IMPLEMENTATION, MS_IOCTL_REVIDR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Reserved", "ident", "REVIDR", "Implementation Defined" },
    
    { BO_V7A_TLBTR_NU, MS_IOCTL_TLBTR, NS_PRIVILEGE_LEVEL_1, 0, 1, "nU", "ident", "TLBTR", "[0] Not Unified TLB" },
    { BO_V7A_TLBTR_IMPLEMENTATION, MS_IOCTL_TLBTR, NS_PRIVILEGE_LEVEL_1, 1, 31, "Implementation Defined", "ident", "TLBTR", "Implementation Defined" },
    
    { BO_V7A_CCSIDR_LINESIZE, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 0, 3, "LineSize", "ident", "CCSIDR", "Number of words in cache line" },
    { BO_V7A_CCSIDR_ASSOCIATIVITY, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 3, 10, "Associativity", "ident", "CCSIDR", "Associativity of cache" },
    { BO_V7A_CCSIDR_NUMSETS, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 13, 15, "NumSets", "ident", "CCSIDR", "Number of sets in cache" },
    { BO_V7A_CCSIDR_WA, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 28, 1, "WA", "ident", "CCSIDR", "Write allocation" },
    { BO_V7A_CCSIDR_RA, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 29, 1, "RA", "ident", "CCSIDR", "Read allocation" },
    { BO_V7A_CCSIDR_WB, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 30, 1, "WB", "ident", "CCSIDR", "Write back" },
    { BO_V7A_CCSIDR_WT, MS_IOCTL_CCSIDR, NS_PRIVILEGE_LEVEL_1, 31, 1, "WT", "ident", "CCSIDR", "Write through" },
    
    { BO_V7A_TCMTR_IMPLEMENTATION, MS_IOCTL_TCMTR, NS_PRIVILEGE_LEVEL_1, 0, 29, "Implementation Defined", "ident", "TCMTR", "Implementation Defined" },
    { BO_V7A_TCMTR_FORMAT, MS_IOCTL_TCMTR, NS_PRIVILEGE_LEVEL_1, 29, 3, "Format", "ident", "TCMTR", "Implemented TCMTR format" },
        
    { BO_V7A_AIDR_IMPLEMENTATION, MS_IOCTL_AIDR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "ident", "AIDR", "Implementation Defined" },
    
    { BO_V7A_CLIDR_CTYPE1, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 0, 3, "Ctype1", "ident", "CLIDR", "Cache type 1" },
    { BO_V7A_CLIDR_CTYPE2, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 3, 3, "Ctype2", "ident", "CLIDR", "Cache type 2" },
    { BO_V7A_CLIDR_CTYPE3, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 6, 3, "Ctype3", "ident", "CLIDR", "Cache type 3" },
    { BO_V7A_CLIDR_CTYPE4, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 9, 3, "Ctype4", "ident", "CLIDR", "Cache type 4" },
    { BO_V7A_CLIDR_CTYPE5, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 12, 3, "Ctype5", "ident", "CLIDR", "Cache type 5" },
    { BO_V7A_CLIDR_CTYPE6, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 15, 3, "Ctype6", "ident", "CLIDR", "Cache type 6" },
    { BO_V7A_CLIDR_CTYPE7, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 18, 3, "Ctype7", "ident", "CLIDR", "Cache type 7" },
    { BO_V7A_CLIDR_LOUIS, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 21, 3, "LoUIS", "ident", "CLIDR", "Level of Unification Inner Shareable" },
    { BO_V7A_CLIDR_LOC, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 24, 3, "LoC", "ident", "CLIDR", "Level of Coherence" },
    { BO_V7A_CLIDR_LOUU, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 27, 3, "LoUU", "ident", "CLIDR", "Level of Unification Uniprocessor" },
    { BO_V7A_CLIDR_RESERVED, MS_IOCTL_CLIDR, NS_PRIVILEGE_LEVEL_1, 30, 2, "Reserved", "ident", "CLIDR", "Reserved" },
    
    { BO_V7A_CSSELR_IND, MS_IOCTL_CSSELR, NS_PRIVILEGE_LEVEL_1, 0, 1, "InD", "ident", "CSSELR", "Instruction not Data bit" },
    { BO_V7A_CSSELR_LEVEL, MS_IOCTL_CSSELR, NS_PRIVILEGE_LEVEL_1, 1, 3, "Level", "ident", "CSSELR", "Level" },
    { BO_V7A_CSSELR_RESERVED, MS_IOCTL_CSSELR, NS_PRIVILEGE_LEVEL_1, 4, 28, "Reserved", "ident", "CSSELR", "Reserved" },
    
    { BO_V7A_CTR_IMINLINE, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 0, 4, "IminLine", "ident", "CTR", "IminLine" },
    { BO_V7A_CTR_RESERVED_01, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 4, 10, "Reserved", "ident", "CTR", "Reserved" },
    { BO_V7A_CTR_L1IP, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 14, 2, "L1Ip", "ident", "CTR", "Level 1 instruction cache policy" },
    { BO_V7A_CTR_DMINLINE, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 16, 4, "DminLine", "ident", "CTR", "DminLine" },
    { BO_V7A_CTR_ERG, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 20, 4, "ERG", "ident", "CTR", "Exclusives Reservation Granule" },
    { BO_V7A_CTR_CWG, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 24, 4, "CWG", "ident", "CTR", "Cache Write-back Granule" },
    { BO_V7A_CTR_RESERVED_02, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 28, 1, "Reserved", "ident", "CTR", "Reserved" },
    { BO_V7A_CTR_FORMAT, MS_IOCTL_CTR, NS_PRIVILEGE_LEVEL_1, 29, 3, "Format", "ident", "CTR", "CTR Format" },
    
    { BO_V7A_MIDR_REVISION, MS_IOCTL_MIDR, NS_PRIVILEGE_LEVEL_1, 0, 4, "Revision", "ident", "MIDR", "Revision" },
    { BO_V7A_MIDR_PARTNUMBER, MS_IOCTL_MIDR, NS_PRIVILEGE_LEVEL_1, 4, 12, "Primary part number", "ident", "MIDR", "Primary part number" },
    { BO_V7A_MIDR_ARCH, MS_IOCTL_MIDR, NS_PRIVILEGE_LEVEL_1, 16, 4, "Architecture", "ident", "MIDR", "Architecture" },
    { BO_V7A_MIDR_VARIANT, MS_IOCTL_MIDR, NS_PRIVILEGE_LEVEL_1, 20, 4, "Variant", "ident", "MIDR", "Variant" },
    { BO_V7A_MIDR_IMPLEMENTER, MS_IOCTL_MIDR, NS_PRIVILEGE_LEVEL_1, 24, 8, "Implementer", "ident", "MIDR", "Implementer" },
    
    { BO_V7A_MPIDR_AFF0, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 0, 8, "Aff0", "ident", "MPIDR", "Affinity level 0" },
    { BO_V7A_MPIDR_AFF1, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 8, 8, "Aff1", "ident", "MPIDR", "Affinity level 1" },
    { BO_V7A_MPIDR_AFF2, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 16, 8, "Aff2", "ident", "MPIDR", "Affinity level 2" },
    { BO_V7A_MPIDR_MT, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 24, 1, "MT", "ident", "MPIDR", "Affinity dependence" },
    { BO_V7A_MPIDR_RESERVED, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 25, 5, "Reserved", "ident", "MPIDR", "Reserved" },
    { BO_V7A_MPIDR_U, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 30, 1, "U", "ident", "MPIDR", "Uniprocessor system" },
    { BO_V7A_MPIDR_ME, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 31, 1, "ME", "ident", "MPIDR", "Register format" },       
                
                
    /* Floating Point Bitfields */
    { BO_V7A_FPSID_REVISION, MS_IOCTL_FPSID, NS_PRIVILEGE_LEVEL_1, 0, 4, "Revision", "fp", "FPSID", "Revision number" },
    { BO_V7A_FPSID_VARIANT, MS_IOCTL_FPSID, NS_PRIVILEGE_LEVEL_1, 4, 4, "Variant", "fp", "FPSID", "Variant number" },
    { BO_V7A_FPSID_PARTNUMBER, MS_IOCTL_FPSID, NS_PRIVILEGE_LEVEL_1, 8, 8, "Part Number", "fp", "FPSID", "Part number" },
    { BO_V7A_FPSID_SUBARCH, MS_IOCTL_FPSID, NS_PRIVILEGE_LEVEL_1, 16, 6, "Subarchitecture", "fp", "FPSID", "Subarchitecture version number" },
    { BO_V7A_FPSID_SW, MS_IOCTL_FPSID, NS_PRIVILEGE_LEVEL_1, 23, 1, "SW", "fp", "FPSID", "Software emulation" },
    { BO_V7A_FPSID_IMPLEMENTER, MS_IOCTL_FPSID, NS_PRIVILEGE_LEVEL_1, 24, 8, "Implementer", "fp", "FPSID", "Implementer" },
    
    { BO_V7A_FPSCR_IOC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 0, 1, "IOC", "fp", "FPSCR", "Invalid Operation cumulative exception" },  
    { BO_V7A_FPSCR_DZC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 1, 1, "DZC", "fp", "FPSCR", "Division by Zero cumulative exception" },   
    { BO_V7A_FPSCR_OFC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 2, 1, "OFC", "fp", "FPSCR", "Overflow cumulative exception" },   
    { BO_V7A_FPSCR_UFC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 3, 1, "UFC", "fp", "FPSCR", "Underflow cumulative exception" },  
    { BO_V7A_FPSCR_IXC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 4, 1, "IXC", "fp", "FPSCR", "Inexact cumulative exception" },
    { BO_V7A_FPSCR_RESERVED_01, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 5, 2, "Reserved", "fp", "FPSCR", "Reserved" },
    { BO_V7A_FPSCR_IDC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 7, 1, "IDC", "fp", "FPSCR", "Input Denormal cumulative exception" },
    { BO_V7A_FPSCR_IOE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 8, 1, "IOE", "fp", "FPSCR", "Invalid Operation exception trap enable" },
    { BO_V7A_FPSCR_DZE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 9, 1, "DZE", "fp", "FPSCR", "Division by Zero exception trap enable" },
    { BO_V7A_FPSCR_OFE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 10, 1, "OFE", "fp", "FPSCR", "Overflow exception trap enable" },
    { BO_V7A_FPSCR_UFE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 11, 1, "UFE", "fp", "FPSCR", "Underflow exception trap enable" },
    { BO_V7A_FPSCR_IXE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 12, 1, "IXE", "fp", "FPSCR", "Inexact exception trap enable" },
    { BO_V7A_FPSCR_RESERVED_02, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 13, 2, "Reserved", "fp", "FPSCR", "Reserved" },
    { BO_V7A_FPSCR_IDE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 15, 1, "IDE", "fp", "FPSCR", "Input Denormal exception trap enable" },
    { BO_V7A_FPSCR_LEN, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 16, 3, "LEN", "fp", "FPSCR", "ARM deprecated field" },
    { BO_V7A_FPSCR_RESERVED_03, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 19, 1, "Reserved", "fp", "FPSCR", "Reserved" },
    { BO_V7A_FPSCR_STRIDE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 20, 2, "Stride", "fp", "FPSCR", "ARM deprecated field" },
    { BO_V7A_FPSCR_RMODE, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 22, 2, "RMode", "fp", "FPSCR", "Rounding Mode control" },
    { BO_V7A_FPSCR_FZ, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 24, 1, "FZ", "fp", "FPSCR", "Flush-to-zero" },
    { BO_V7A_FPSCR_DN, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 25, 1, "DN", "fp", "FPSCR", "Default NaN" },
    { BO_V7A_FPSCR_AHP, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 26, 1, "AHP", "fp", "FPSCR", "Alternative half-precision" },
    { BO_V7A_FPSCR_QC, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 27, 1, "QC", "fp", "FPSCR", "Cumulative saturation bit" },
    { BO_V7A_FPSCR_V, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 28, 1, "V", "fp", "FPSCR", "Overflow condition flag" },
    { BO_V7A_FPSCR_C, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 29, 1, "C", "fp", "FPSCR", "Carry condition flag" },
    { BO_V7A_FPSCR_Z, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 30, 1, "Z", "fp", "FPSCR", "Zero condition flag" },
    { BO_V7A_FPSCR_N, MS_IOCTL_FPSCR, NS_PRIVILEGE_LEVEL_1, 31, 1, "N", "fp", "FPSCR", "Negative condition flag" },
    
    { BO_V7A_FPEXC_IMPLEMENTATION, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 0, 29, "Implementation Defined", "fp", "FPEXC", "Subarchitecture defined" },
    { BO_V7A_FPEXC_EN, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 30, 1, "EN", "fp", "FPEXC", "Global enable for Advanced SIMD and Floating-point Extensions" },
    { BO_V7A_FPEXC_EX, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 31, 1, "EX", "fp", "FPEXC", "Extent of saved records for Advanced SIMD and Floating-point systems" },
    
    { BO_V7A_MVFR0_ASIMD, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 0, 4, "A_SIMD registers", "fp", "MVFR0", "Support for Advanced SIMD register bank" },
    { BO_V7A_MVFR0_SINGLEPRECISION, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 4, 4, "Single-precision", "fp", "MVFR0", "Support for Floating-point Extension single-precision operations" },
    { BO_V7A_MVFR0_DOUBLEPRECISION, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 8, 4, "Double-precision", "fp", "MVFR0", "Support for Floating-point Extension double-precision operations" },
    { BO_V7A_MVFR0_VFPTRAPPING, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 12, 4, "VFP exception exception trapping", "fp", "MVFR0", "VFP support for exception handling" },
    { BO_V7A_MVFR0_DIVIDE, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 16, 4, "Divide", "fp", "MVFR0", "VFP divide support" },
    { BO_V7A_MVFR0_SQUAREROOT, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 20, 4, "Square root", "fp", "MVFR0", "VFP square root support" },
    { BO_V7A_MVFR0_SHORTVECTORS, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 24, 4, "Short vectors", "fp", "MVFR0", "VFP short vector support" },
    { BO_V7A_MVFR0_VFPROUNDING, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 28, 4, "VFP rounding modes", "fp", "MVFR0", "VFP rounding modes support" },
    
    { BO_V7A_MVFR1_FTZ, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 0, 4, "FtZ mode", "fp", "MVFR1", "Flush-to-zero only" },
    { BO_V7A_MVFR1_DNAN, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 4, 4, "D_NaN", "fp", "MVFR1", "Default NaN only" },
    { BO_V7A_MVFR1_ASIMDLOAD, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 8, 4, "A_SIMD load/store", "fp", "MVFR1", "A_SIMD Load/store implementation" },
    { BO_V7A_MVFR1_ASIMDINT, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 12, 4, "A_SIMD integer", "fp", "MVFR1", "A_SIMD integer instructions" },
    { BO_V7A_MVFR1_ASIMDSPFP, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 16, 4, "A_SIMD SPFP", "fp", "MVFR1", "A_SIMD single-precision floating point conversion" },
    { BO_V7A_MVFR1_ASIMDHPFP, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 20, 4, "A_SIMD HPFP", "fp", "MVFR1", "A_SIMD half-precision floating point conversion" },
    { BO_V7A_MVFR1_VFPHPFP, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 24, 4, "VFP HPFP", "fp", "MVFR1", "Floating point implements half-precision floating-point conversion" },
    { BO_V7A_MVFR1_ASIMDFMAC, MS_IOCTL_FPEXC, NS_PRIVILEGE_LEVEL_1, 28, 4, "A_SIMD FMAC", "fp", "MVFR1", "FP or A_SIMD implements fused multiply accumulate" },
                
    /* Security Extension Bitfields */
    { BO_V7A_SCR_NS, MS_IOCTL_SCR, S_ALL, 0, 1, "NS", "secext", "SCR", "Non Secure Bit" },
    { BO_V7A_SCR_IRQ, MS_IOCTL_SCR, S_ALL, 1, 1, "IRQ", "secext", "SCR", "IRQ Handler" },
    { BO_V7A_SCR_FIQ, MS_IOCTL_SCR, S_ALL, 2, 1, "FIQ", "secext", "SCR", "FIQ Handler" },
    { BO_V7A_SCR_EA, MS_IOCTL_SCR, S_ALL, 3, 1, "EA", "secext", "SCR", "External Abort Handler" },
    { BO_V7A_SCR_FW, MS_IOCTL_SCR, S_ALL, 4, 1, "FW", "secext", "SCR", "F bit writeable" },
    { BO_V7A_SCR_AW, MS_IOCTL_SCR, S_ALL, 5, 1, "AW", "secext", "SCR", "A bit writeable" },
    { BO_V7A_SCR_NET, MS_IOCTL_SCR, S_ALL, 6, 1, "nET", "secext", "SCR", "Not Early Termination" },
    { BO_V7A_SCR_SCD, MS_IOCTL_SCR, S_ALL, 7, 1, "SCD", "secext", "SCR", "Secure Monitor Call disable" },
    { BO_V7A_SCR_HCE, MS_IOCTL_SCR, S_ALL, 8, 1, "HCE", "secext", "SCR", "HYP call enable" },
    { BO_V7A_SCR_SIF, MS_IOCTL_SCR, S_ALL, 9, 1, "SIF", "secext", "SCR", "Secure Instruction Fetch bit" },
    { BO_V7A_SCR_RESERVED, MS_IOCTL_SCR, S_ALL, 10, 22, "Reserved", "secext", "SCR", "Reserved" },
    
    { BO_V7A_ISR_RESERVED_01, MS_IOCTL_ISR, NS_PRIVILEGE_LEVEL_1, 0, 6, "Reserved", "secext", "ISR", "Reserved" },
    { BO_V7A_ISR_F, MS_IOCTL_ISR, NS_PRIVILEGE_LEVEL_1, 6, 1, "F", "secext", "ISR", "FIQ pending bit" },
    { BO_V7A_ISR_I, MS_IOCTL_ISR, NS_PRIVILEGE_LEVEL_1, 7, 1, "I", "secext", "ISR", "IRQ pending bit" },
    { BO_V7A_ISR_A, MS_IOCTL_ISR, NS_PRIVILEGE_LEVEL_1, 8, 1, "A", "secext", "ISR", "External abort pending bit" },
    { BO_V7A_ISR_RESERVED_02, MS_IOCTL_ISR, NS_PRIVILEGE_LEVEL_1, 9, 23, "Reserved", "secext", "ISR", "Reserved" },
    
    { BO_V7A_MVBAR_RESERVED, MS_IOCTL_MVBAR, S_ALL, 0, 5, "Reserved", "secext", "MVBAR", "Reserved" },
    { BO_V7A_MVBAR_MVB, MS_IOCTL_MVBAR, S_ALL, 5, 27, "Monitor_Vector_Base_Address", "secext", "MVBAR", "Monitor Vector Base Address" },
    
    { BO_V7A_NSACR_CP0, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 0, 1, "CP0", "secext", "NSACR", "Non-secure access to coprocessor 0 enable" },
    { BO_V7A_NSACR_CP1, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 1, 1, "CP1", "secext", "NSACR", "Non-secure access to coprocessor 1 enable" },
    { BO_V7A_NSACR_CP2, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 2, 1, "CP2", "secext", "NSACR", "Non-secure access to coprocessor 2 enable" },
    { BO_V7A_NSACR_CP3, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 3, 1, "CP3", "secext", "NSACR", "Non-secure access to coprocessor 3 enable" },
    { BO_V7A_NSACR_CP4, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 4, 1, "CP4", "secext", "NSACR", "Non-secure access to coprocessor 4 enable" },
    { BO_V7A_NSACR_CP5, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 5, 1, "CP5", "secext", "NSACR", "Non-secure access to coprocessor 5 enable" },
    { BO_V7A_NSACR_CP6, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 6, 1, "CP6", "secext", "NSACR", "Non-secure access to coprocessor 6 enable" },
    { BO_V7A_NSACR_CP7, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 7, 1, "CP7", "secext", "NSACR", "Non-secure access to coprocessor 7 enable" },
    { BO_V7A_NSACR_CP8, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 8, 1, "CP8", "secext", "NSACR", "Non-secure access to coprocessor 8 enable" },
    { BO_V7A_NSACR_CP9, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 9, 1, "CP9", "secext", "NSACR", "Non-secure access to coprocessor 9 enable" },
    { BO_V7A_NSACR_CP10, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 10, 1, "CP10", "secext", "NSACR", "Non-secure access to coprocessor 10 enable" },
    { BO_V7A_NSACR_CP11, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 11, 1, "CP11", "secext", "NSACR", "Non-secure access to coprocessor 11 enable" },
    { BO_V7A_NSACR_CP12, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 12, 1, "CP12", "secext", "NSACR", "Non-secure access to coprocessor 12 enable" },
    { BO_V7A_NSACR_CP13, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 13, 1, "CP13", "secext", "NSACR", "Non-secure access to coprocessor 13 enable" },
    { BO_V7A_NSACR_NSD32DIS, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 14, 1, "NSD32DIS", "secext", "NSACR", "Disable non-secure use of registers" },
    { BO_V7A_NSACR_NSASEDIS, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 15, 1, "NSASEDIS", "secext", "NSACR", "Disable non-secure advanced SIMD" },
    { BO_V7A_NSACR_IMPLEMENTATION, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 16, 3, "Implementation Defined", "secext", "NSACR", "Implementation defined" },
    { BO_V7A_NSACR_RFR, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 19, 1, "RFR", "secext", "NSACR", "Reserve FIQ Resisters" },
    { BO_V7A_NSACR_NSTRCDIS, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 20, 1, "NSTRCDIS", "secext", "NSACR", "Disable non-secure access to CP14 trace registers" },
    { BO_V7A_NSACR_RESERVED, MS_IOCTL_NSACR, NS_PRIVILEGE_LEVEL_1, 21, 11, "Reserved", "secext", "NSACR", "Reserved" },
    
    { BO_V7A_SDER_SUIDEN, MS_IOCTL_SDER, S_ALL, 0, 1, "SUIDEN", "secext", "SDER", "Secure user invasive debug" },
    { BO_V7A_SDER_SUNIDEN, MS_IOCTL_SDER, S_ALL, 1, 1, "SUNIDEN", "secext", "SDER", "Secure user non-invasive debug" },
    { BO_V7A_SDER_RESERVED, MS_IOCTL_SDER, S_ALL, 2, 30, "Reserved", "secext", "SDER", "Reserved" },
    
    { BO_V7A_VBAR_RESERVED, MS_IOCTL_VBAR, NS_PRIVILEGE_LEVEL_1, 0, 5, "Reserved", "secext", "VBAR", "Reserved" },
    { BO_V7A_VBAR_VBA, MS_IOCTL_VBAR, NS_PRIVILEGE_LEVEL_1, 5, 27, "Reserved", "secext", "VBAR", "Vector base address" },
    
    /* Debug Bitfields */
    { BO_V7A_DBGDIDR_REVISION, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 0, 4, "Revision", "debug", "DBGDIDR", "Revision" },
    { BO_V7A_DBGDIDR_VARIANT, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 4, 4, "Variant", "debug", "DBGDIDR", "Variant" },
    { BO_V7A_DBGDIDR_RESERVED, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 8, 4, "Reserved", "debug", "DBGDIDR", "Reserved" },
    { BO_V7A_DBGDIDR_SE_IMP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 12, 1, "SE_imp", "debug", "DBGDIDR", "Security Extensions Implemented" },
    { BO_V7A_DBGDIDR_PCSR_IMP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 13, 1, "PCSR_imp", "debug", "DBGDIDR", "Program Counter Sampling Register" },
    { BO_V7A_DBGDIDR_NSUHD_IMP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 14, 1, "nSUHD_imp", "debug", "DBGDIDR", "Secure User Halting Debug" },
    { BO_V7A_DBGDIDR_DEVID_IMP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 15, 1, "DEVID_imp", "debug", "DBGDIDR", "Debug Device ID" },
    { BO_V7A_DBGDIDR_VERSION, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 16, 4, "Version", "debug", "DBGDIDR", "Version" },
    { BO_V7A_DBGDIDR_CTX_CMP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 20, 4, "CTX_CMP", "debug", "DBGDIDR", "Context Compare Breakpoints" },
    { BO_V7A_DBGDIDR_BRP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 24, 4, "BRP", "debug", "DBGDIDR", "Number of breakpoints" },
    { BO_V7A_DBGDIDR_WRP, MS_IOCTL_DBGDIDR, NS_PRIVILEGE_LEVEL_1, 28, 4, "WRP", "debug", "DBGDIDR", "Number of Watchpoints Implemented" },
    
    { BO_V7A_DBGAUTHSTATUS_NSE, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 0, 1, "NSE", "debug", "DBGAUTHSTATUS", "Non-secure invasive debug" },
    { BO_V7A_DBGAUTHSTATUS_NSI, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 1, 1, "NSI", "debug", "DBGAUTHSTATUS", " Non-secure invasive debug features" },
    { BO_V7A_DBGAUTHSTATUS_NSNE, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 2, 1, "NSNE", "debug", "DBGAUTHSTATUS", "Non-secure non-invasive debug" },
    { BO_V7A_DBGAUTHSTATUS_NSNI, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 3, 1, "NSNI", "debug", "DBGAUTHSTATUS", "Non-secure non-invasive debug" },
    { BO_V7A_DBGAUTHSTATUS_SE, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 4, 1, "SE", "debug", "DBGAUTHSTATUS", "Secure invasive" },
    { BO_V7A_DBGAUTHSTATUS_SI, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 5, 1, "SI", "debug", "DBGAUTHSTATUS", "Secure invasive features" },
    { BO_V7A_DBGAUTHSTATUS_SNE, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 6, 1, "SNE", "debug", "DBGAUTHSTATUS", "Secure non-invasive" },
    { BO_V7A_DBGAUTHSTATUS_SNI, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 7, 1, "SNI", "debug", "DBGAUTHSTATUS", "Secure non-invasive features" },
    { BO_V7A_DBGAUTHSTATUS_RESERVED, MS_IOCTL_DBGAUTHSTATUS, NS_PRIVILEGE_LEVEL_1, 8, 24, "Reserved", "debug", "DBGAUTHSTATUS", "Reserved" },
    
    { BO_V7A_DBGDRAR_VALID, MS_IOCTL_DBGDRAR, NS_PRIVILEGE_LEVEL_1, 0, 2, "Valid", "debug", "DBGDRAR", "ROM table address is valid" },
    { BO_V7A_DBGDRAR_RESERVED_01, MS_IOCTL_DBGDRAR, NS_PRIVILEGE_LEVEL_1, 2, 10, "Reserved", "debug", "DBGDRAR", "Reserved" },
    { BO_V7A_DBGDRAR_ROMADDR, MS_IOCTL_DBGDRAR, NS_PRIVILEGE_LEVEL_1, 12, 28, "ROMADDR", "debug", "DBGDRAR", "Bits [39:12] of component physical address. [11:0] are zero." },
    { BO_V7A_DBGDRAR_RESERVED_02, MS_IOCTL_DBGDRAR, NS_PRIVILEGE_LEVEL_1, 40, 24, "Reserved", "debug", "DBGDRAR", "Reserved" },
    
    { BO_V7A_DBGDSCR_HALTED, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 0, 1, "HALTED", "debug", "DBGDSCR", "Processor Halted" },
    { BO_V7A_DBGDSCR_RESTARTED, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 1, 1, "RESTARTED", "debug", "DBGDSCR", "Processor Restarted" },
    { BO_V7A_DBGDSCR_MOE, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 2, 4, "MOE", "debug", "DBGDSCR", "Method of debug entry" },
    { BO_V7A_DBGDSCR_SDABORT_L, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 6, 1, "SDABORT_L", "debug", "DBGDSCR", "Synchronous data abort exception when in debug state" },
    { BO_V7A_DBGDSCR_ADABORT_L, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 7, 1, "ADABORT_L", "debug", "DBGDSCR", "Asynchronous data abort exception when in debug state" },
    { BO_V7A_DBGDSCR_UND_L, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 8, 1, "UND_L", "debug", "DBGDSCR", "Undefined instruction exception when in debug state" },
    { BO_V7A_DBGDSCR_FS, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 9, 1, "FS", "debug", "DBGDSCR", "Updated every data abort exception generated in debug state" },
    { BO_V7A_DBGDSCR_DBGACK, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 10, 1, "DBGack", "debug", "DBGDSCR", "Force debug acknowledge" },
    { BO_V7A_DBGDSCR_INTDIS, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 11, 1, "INTdis", "debug", "DBGDSCR", "Interrupts disable" },
    { BO_V7A_DBGDSCR_UDCCDIS, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 12, 1, "UDCCDIS", "debug", "DBGDSCR", "User mode access to Debug Communications Channel (DBB) disable" },
    { BO_V7A_DBGDSCR_ITREN, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 13, 1, "ITRen", "debug", "DBGDSCR", "Enabled execution of ARM instructions through the DBGITR" },
    { BO_V7A_DBGDSCR_HDBGEN, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 14, 1, "HDBGen", "debug", "DBGDSCR", "Halting debug-mode enable" },
    { BO_V7A_DBGDSCR_MDBGEN, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 15, 1, "MDGBen", "debug", "DBGDSCR", "Monitor debug-mode enable" },
    { BO_V7A_DBGDSCR_SPIDDIS, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 16, 1, "SPIDdis", "debug", "DBGDSCR", "Secure PL1 invasive debug disabled bit" },
    { BO_V7A_DBGDSCR_SPNIDIS, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 17, 1, "SPNIdis", "debug", "DBGDSCR", "Secure PL1 non-invasive debug disabled bit" },
    { BO_V7A_DBGDSCR_NS, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 18, 1, "NS", "debug", "DBGDSCR", "Non-secure state status" },
    { BO_V7A_DBGDSCR_ADADISCARD, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 19, 1, "ADAdiscard", "debug", "DBGDSCR", "Asynchronous aborts discarded" },
    { BO_V7A_DBGDSCR_EXTDCCMODE, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 20, 2, "ExtDCCmode", "debug", "DBGDSCR", "External DCC access mode" },
    { BO_V7A_DBGDSCR_RESERVED_01, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 22, 2, "Reserved", "debug", "DBGDSCR", "Reserved" },
    { BO_V7A_DBGDSCR_INSTRCOMPL_L, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 24, 1, "InstrCompl_I", "debug", "DBGDSCR", "Latched copy of InstrCompl. Indicates completion of DBGITR" },
    { BO_V7A_DBGDSCR_PIPEADV, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 25, 1, "PipeAdv", "debug", "DBGDSCR", "Stick pipeline advance bit" },
    { BO_V7A_DBGDSCR_TXFULL_L, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 26, 1, "TXfull_L", "debug", "DBGDSCR", "Controls behavior of processor on reads of DBGDTRTXext" },
    { BO_V7A_DBGDSCR_RXFULL_L, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 27, 1, "RXfull_L", "debug", "DBGDSCR", "Controls behavior of processor on reads of DBGDTRRXext" },
    { BO_V7A_DBGDSCR_RESERVED_02, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 28, 1, "Reserved", "debug", "DBGDSCR", "Reserved" }, 
    { BO_V7A_DBGDSCR_TXFULL, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 29, 1, "TXfull", "debug", "DBGDSCR", "DBGDTRTX register full" },
    { BO_V7A_DBGDSCR_RXFULL, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 30, 1, "RXfull", "debug", "DBGDSCR", "DBGDTRTX register full" },
    { BO_V7A_DBGDSCR_RESERVED_03, MS_IOCTL_DBGDSCR, NS_PRIVILEGE_LEVEL_1, 31, 1, "Reserved", "debug", "DBGDSCR", "Reserved" },     
        
    /* Virtual Memory Bitfields */  
    { BO_V7A_NMRR_IR0, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 0, 2, "IR0", "virtmem", "NMRR", "Inner Cacheable property 0" },
    { BO_V7A_NMRR_IR1, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 2, 2, "IR1", "virtmem", "NMRR", "Inner Cacheable property 1" },
    { BO_V7A_NMRR_IR2, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 4, 2, "IR2", "virtmem", "NMRR", "Inner Cacheable property 2" },
    { BO_V7A_NMRR_IR3, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 6, 2, "IR3", "virtmem", "NMRR", "Inner Cacheable property 3" },
    { BO_V7A_NMRR_IR4, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 8, 2, "IR4", "virtmem", "NMRR", "Inner Cacheable property 4" },
    { BO_V7A_NMRR_IR5, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 10, 2, "IR5", "virtmem", "NMRR", "Inner Cacheable property 5" },
    { BO_V7A_NMRR_IR6, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 12, 2, "IR6", "virtmem", "NMRR", "Inner Cacheable property 6" },
    { BO_V7A_NMRR_IR7, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 14, 2, "IR7", "virtmem", "NMRR", "Inner Cacheable property 7" },
    { BO_V7A_NMRR_OR0, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 16, 2, "OR0", "virtmem", "NMRR", "Outer Cacheable property 0" },
    { BO_V7A_NMRR_OR1, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 18, 2, "OR1", "virtmem", "NMRR", "Outer Cacheable property 1" },
    { BO_V7A_NMRR_OR2, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 20, 2, "OR2", "virtmem", "NMRR", "Outer Cacheable property 2" },
    { BO_V7A_NMRR_OR3, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 22, 2, "OR3", "virtmem", "NMRR", "Outer Cacheable property 3" },
    { BO_V7A_NMRR_OR4, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 24, 2, "OR4", "virtmem", "NMRR", "Outer Cacheable property 4" },
    { BO_V7A_NMRR_OR5, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 26, 2, "OR5", "virtmem", "NMRR", "Outer Cacheable property 5" },
    { BO_V7A_NMRR_OR6, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 28, 2, "OR6", "virtmem", "NMRR", "Outer Cacheable property 6" },
    { BO_V7A_NMRR_OR7, MS_IOCTL_NMRR, NS_PRIVILEGE_LEVEL_1, 30, 2, "OR7", "virtmem", "NMRR", "Outer Cacheable property 7" },

    { BO_V7A_PRRR_TR0, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 0, 2, "TR0", "virtmem", "PRRR", "Memory TEX mapping 0" },
    { BO_V7A_PRRR_TR1, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 2, 2, "TR1", "virtmem", "PRRR", "Memory TEX mapping 1" },
    { BO_V7A_PRRR_TR2, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 4, 2, "TR2", "virtmem", "PRRR", "Memory TEX mapping 2" },
    { BO_V7A_PRRR_TR3, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 6, 2, "TR3", "virtmem", "PRRR", "Memory TEX mapping 3" },
    { BO_V7A_PRRR_TR4, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 8, 2, "TR4", "virtmem", "PRRR", "Memory TEX mapping 4" },
    { BO_V7A_PRRR_TR5, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 10, 2, "TR5", "virtmem", "PRRR", "Memory TEX mapping 5" },
    { BO_V7A_PRRR_TR6, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 12, 2, "TR6", "virtmem", "PRRR", "Memory TEX mapping 6" },
    { BO_V7A_PRRR_TR7, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 14, 2, "TR7", "virtmem", "PRRR", "Memory TEX mapping 7" },
    { BO_V7A_PRRR_DS0, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 16, 1, "DS0", "virtmem", "PRRR", "Mapping of S = 0 attribute for device memory" },
    { BO_V7A_PRRR_DS1, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 17, 1, "DS1", "virtmem", "PRRR", "Mapping of S = 1 attribute for device memory" },
    { BO_V7A_PRRR_NS0, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 18, 1, "NS0", "virtmem", "PRRR", "Mapping of S = 0 attribute for normal memory" },
    { BO_V7A_PRRR_NS1, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 19, 1, "NS1", "virtmem", "PRRR", "Mapping of S = 1 attribute for normal memory" },
    { BO_V7A_PRRR_RESERVED, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 20, 4, "Reserved", "virtmem", "PRRR", "Reserved" },
    { BO_V7A_PRRR_NOS0, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 24, 1, "NOS0", "virtmem", "PRRR", "Outer Shareable property mapping 0" },
    { BO_V7A_PRRR_NOS1, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 25, 1, "NOS1", "virtmem", "PRRR", "Outer Shareable property mapping 1" },
    { BO_V7A_PRRR_NOS2, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 26, 1, "NOS2", "virtmem", "PRRR", "Outer Shareable property mapping 2" },
    { BO_V7A_PRRR_NOS3, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 27, 1, "NOS3", "virtmem", "PRRR", "Outer Shareable property mapping 3" },
    { BO_V7A_PRRR_NOS4, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 28, 1, "NOS4", "virtmem", "PRRR", "Outer Shareable property mapping 4" },
    { BO_V7A_PRRR_NOS5, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 29, 1, "NOS5", "virtmem", "PRRR", "Outer Shareable property mapping 5" },
    { BO_V7A_PRRR_NOS6, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 30, 1, "NOS6", "virtmem", "PRRR", "Outer Shareable property mapping 6" },
    { BO_V7A_PRRR_NOS7, MS_IOCTL_PRRR, NS_PRIVILEGE_LEVEL_1, 31, 1, "NOS7", "virtmem", "PRRR", "Outer Shareable property mapping 7" },
    
    { BO_V7A_SCTLR_M, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 0, 1, "M", "virtmem", "SCTLR", "MMU Enable" },
    { BO_V7A_SCTLR_A, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 1, 1, "A", "virtmem", "SCTLR", "Alignment check enable" },
    { BO_V7A_SCTLR_C, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 2, 1, "C", "virtmem", "SCTLR", "Cache enable" },
    { BO_V7A_SCTLR_RESERVED_01, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 3, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_CP15BEN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "CP15BEN", "virtmem", "SCTLR", "CP15 barrier enable" },
    { BO_V7A_SCTLR_RESERVED_02, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_B, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 7, 1, "B", "virtmem", "SCTLR", "Endianess" },
    { BO_V7A_SCTLR_RESERVED_03, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 8, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_SW, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 10, 1, "SW", "virtmem", "SCTLR", "SWP and SWPB enable" },
    { BO_V7A_SCTLR_Z, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 11, 1, "Z", "virtmem", "SCTLR", "Branch prediction enable" },
    { BO_V7A_SCTLR_I, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 12, 1, "I", "virtmem", "SCTLR", "Instruction cache enable" },
    { BO_V7A_SCTLR_V, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 13, 1, "V", "virtmem", "SCTLR", "Vectors bit" },
    { BO_V7A_SCTLR_RR, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 14, 1, "RR", "virtmem", "SCTLR", "Round Robin select" },
    { BO_V7A_SCTLR_RESERVED_04, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 15, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_RESERVED_05, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 16, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_HA, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 17, 1, "A", "virtmem", "SCTLR", "Hardware access flag enable" },
    { BO_V7A_SCTLR_RESERVED_06, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 18, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_WXN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 19, 1, "WXN", "virtmem", "SCTLR", "Write permission implies XN" },
    { BO_V7A_SCTLR_UWXN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 20, 1, "UWXN", "virtmem", "SCTLR", "Unprivileged write permission implies PL1 XN" },
    { BO_V7A_SCTLR_FI, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "FI", "virtmem", "SCTLR", "Fast interrupts configuration enable" },
    { BO_V7A_SCTLR_U, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 22, 1, "U", "virtmem", "SCTLR", "Alignment model" },
    { BO_V7A_SCTLR_RESERVED_07, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 23, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_VE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "VE", "virtmem", "SCTLR", "Interrupt Vectors enable" },
    { BO_V7A_SCTLR_EE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 25, 1, "EE", "virtmem", "SCTLR", "Exception Endianess" },
    { BO_V7A_SCTLR_RESERVED_08, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 26, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_V7A_SCTLR_NMFI, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 27, 1, "NMFI", "virtmem", "SCTLR", "Non-maskable FIQ support" },
    { BO_V7A_SCTLR_TRE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 28, 1, "TRE", "virtmem", "SCTLR", "TEX remap enable" },
    { BO_V7A_SCTLR_AFE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 29, 1, "AFE", "virtmem", "SCTLR", "Access flag enable" },
    { BO_V7A_SCTLR_TE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 30, 1, "TE", "virtmem", "SCTLR", "Thumb Exception enable" },
    { BO_V7A_SCTLR_RESERVED_09, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 31, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    
    { BO_V7A_TTBCR_N, MS_IOCTL_TTBCR, NS_PRIVILEGE_LEVEL_1, 0, 3, "N", "virtmem", "TTBCR", "Reserved" },
    { BO_V7A_TTBCR_RESERVED_01, MS_IOCTL_TTBCR, NS_PRIVILEGE_LEVEL_1, 3, 1, "Reserved", "virtmem", "TTBCR", "Reserved" },
    { BO_V7A_TTBCR_PD0, MS_IOCTL_TTBCR, NS_PRIVILEGE_LEVEL_1, 4, 1, "PD0", "virtmem", "TTBCR", "Reserved" },
    { BO_V7A_TTBCR_PD1, MS_IOCTL_TTBCR, NS_PRIVILEGE_LEVEL_1, 5, 1, "PD1", "virtmem", "TTBCR", "Reserved" },
    { BO_V7A_TTBCR_RESERVED_02, MS_IOCTL_TTBCR, NS_PRIVILEGE_LEVEL_1, 6, 25, "Reserved", "virtmem", "TTBCR", "Reserved" },
    { BO_V7A_TTBCR_EAE, MS_IOCTL_TTBCR, NS_PRIVILEGE_LEVEL_1, 31, 1, "EAE", "virtmem", "TTBCR", "Reserved" },
    
    { BO_V7A_TTBR0_IRGN_1, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 0, 1 , "IRGN_1", "virtmem", "TTBR0", "Inner Cacheability attributes" },
    { BO_V7A_TTBR0_S, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 1, 1 , "S", "virtmem", "TTBR0", "Shareable attribute" },
    { BO_V7A_TTBR0_IMPLEMENTATION, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 2, 1 , "Implementation Defined", "virtmem", "TTBR0", "Implementation Defined" },
    { BO_V7A_TTBR0_RGN, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 3, 2 , "RGN", "virtmem", "TTBR0", "Outer Cacheability attributes" },
    { BO_V7A_TTBR0_NOS, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 5, 1 , "NOS", "virtmem", "TTBR0", "Outer Shareable attributes" },
    { BO_V7A_TTBR0_IRGN_0, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 6, 1 , "IRGN_0", "virtmem", "TTBR0", "Inner Cacheability attributes" },
    { BO_V7A_TTBR0_TTB0A, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 7, 25 , "TTB0A", "virtmem", "TTBR0", "Translation table base 0 address or Reserved" },
    
    { BO_V7A_TTBR0LPAE_IMPLEMENTATION, MS_IOCTL_TTBR0LPAE, NS_PRIVILEGE_LEVEL_1, 0, 64 , "Implementation Defined", "virtmem", "TTBR0", "Refer to TRM for register format" },

    { BO_V7A_TTBR1_IRGN_1, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 0, 1 , "IRGN_1", "virtmem", "TTBR1", "Inner Cacheability attributes" },
    { BO_V7A_TTBR1_S, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 1, 1 , "S", "virtmem", "TTBR1", "Shareable attribute" },
    { BO_V7A_TTBR1_IMPLEMENTATION, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 2, 1 , "Implementation Defined", "virtmem", "TTBR1", "Implementation Defined" },
    { BO_V7A_TTBR1_RGN, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 3, 2 , "RGN", "virtmem", "TTBR1", "Outer Cacheability attributes" },
    { BO_V7A_TTBR1_NOS, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 5, 1 , "NOS", "virtmem", "TTBR1", "Outer Shareable attributes" },
    { BO_V7A_TTBR1_IRGN_0, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 6, 1 , "IRGN_0", "virtmem", "TTBR1", "Inner Cacheability attributes" },
    { BO_V7A_TTBR1_TTB1A, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 7, 25 , "TTB1A", "virtmem", "TTBR1", "Translation table base 1 address or Reserved" },
    
    { BO_V7A_TTBR1LPAE_IMPLEMENTATION, MS_IOCTL_TTBR1LPAE, NS_PRIVILEGE_LEVEL_1, 0, 64 , "Implementation Defined", "virtmem", "TTBR1", "Refer to TRM for register format" },

    { BO_V7A_CONTEXTIDR_LONG_PROCID, MS_IOCTL_CONTEXTIDR, NS_PRIVILEGE_LEVEL_1, 0, 32, "PROCID", "virtmem", "CONTEXTIDR", "PROCID" },
    { BO_V7A_CONTEXTIDR_SHORT_ASID, MS_IOCTL_CONTEXTIDR, NS_PRIVILEGE_LEVEL_1, 0, 8, "ASID", "virtmem", "CONTEXTIDR", "ASID" },
    { BO_V7A_CONTEXTIDR_SHORT_PROCID, MS_IOCTL_CONTEXTIDR, NS_PRIVILEGE_LEVEL_1, 8, 24, "PROCID", "virtmem", "CONTEXTIDR", "PROCID" }, 
    
    { BO_V7A_AMAIR0_IMPLEMENTATION, MS_IOCTL_AMAIR0, NS_PRIVILEGE_LEVEL_1, 0, 32, "AMAIR0", "virtmem", "AMAIR0", "Implementation Defined" },   
    
    { BO_V7A_AMAIR1_IMPLEMENTATION, MS_IOCTL_AMAIR1, NS_PRIVILEGE_LEVEL_1, 0, 32, "AMAIR1", "virtmem", "AMAIR1", "Implementation Defined" },   
    
    { BO_V7A_DACR_D0, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 0, 2, "D0", "virtmem", "DACR", "Domain 0 access permission" },
    { BO_V7A_DACR_D1, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 2, 2, "D1", "virtmem", "DACR", "Domain 1 access permission" },
    { BO_V7A_DACR_D2, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 4, 2, "D2", "virtmem", "DACR", "Domain 2 access permission" },
    { BO_V7A_DACR_D3, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 6, 2, "D3", "virtmem", "DACR", "Domain 3 access permission" },
    { BO_V7A_DACR_D4, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 8, 2, "D4", "virtmem", "DACR", "Domain 4 access permission" },
    { BO_V7A_DACR_D5, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 10, 2, "D5", "virtmem", "DACR", "Domain 5 access permission" },
    { BO_V7A_DACR_D6, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 12, 2, "D6", "virtmem", "DACR", "Domain 6 access permission" },
    { BO_V7A_DACR_D7, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 14, 2, "D7", "virtmem", "DACR", "Domain 7 access permission" },
    { BO_V7A_DACR_D8, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 16, 2, "D8", "virtmem", "DACR", "Domain 8 access permission" },
    { BO_V7A_DACR_D9, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 18, 2, "D9", "virtmem", "DACR", "Domain 9 ccess permission" },
    { BO_V7A_DACR_D10, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 20, 2, "D10", "virtmem", "DACR", "Domain 10 access permission" },
    { BO_V7A_DACR_D11, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 22, 2, "D11", "virtmem", "DACR", "Domain 11 access permission" },
    { BO_V7A_DACR_D12, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 24, 2, "D12", "virtmem", "DACR", "Domain 12 access permission" },
    { BO_V7A_DACR_D13, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 26, 2, "D13", "virtmem", "DACR", "Domain 13 access permission" },
    { BO_V7A_DACR_D14, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 28, 2, "D14", "virtmem", "DACR", "Domain 14 access permission" },
    { BO_V7A_DACR_D15, MS_IOCTL_DACR, NS_PRIVILEGE_LEVEL_1, 30, 2, "D15", "virtmem", "DACR", "Domain 15 access permission" },
    
    { BO_V7A_MAIR0_ATTR0, MS_IOCTL_MAIR0, NS_PRIVILEGE_LEVEL_1, 0, 8, "Attr0", "virtmem", "MAIR0", "Memory attribute 0 encoding" },
    { BO_V7A_MAIR0_ATTR1, MS_IOCTL_MAIR0, NS_PRIVILEGE_LEVEL_1, 8, 8, "Attr1", "virtmem", "MAIR0", "Memory attribute 1 encoding" },
    { BO_V7A_MAIR0_ATTR2, MS_IOCTL_MAIR0, NS_PRIVILEGE_LEVEL_1, 16, 8, "Attr2", "virtmem", "MAIR0", "Memory attribute 2 encoding" },
    { BO_V7A_MAIR0_ATTR3, MS_IOCTL_MAIR0, NS_PRIVILEGE_LEVEL_1, 24, 8, "Attr3", "virtmem", "MAIR0", "Memory attribute 3 encoding" },
    
    { BO_V7A_MAIR1_ATTR4, MS_IOCTL_MAIR1, NS_PRIVILEGE_LEVEL_1, 0, 8, "Attr4", "virtmem", "MAIR1", "Memory attribute 4 encoding" },
    { BO_V7A_MAIR1_ATTR5, MS_IOCTL_MAIR1, NS_PRIVILEGE_LEVEL_1, 8, 8, "Attr5", "virtmem", "MAIR1", "Memory attribute 5 encoding" },
    { BO_V7A_MAIR1_ATTR6, MS_IOCTL_MAIR1, NS_PRIVILEGE_LEVEL_1, 16, 8, "Attr6", "virtmem", "MAIR1", "Memory attribute 6 encoding" },
    { BO_V7A_MAIR1_ATTR7, MS_IOCTL_MAIR1, NS_PRIVILEGE_LEVEL_1, 24, 8, "Attr7", "virtmem", "MAIR1", "Memory attribute 7 encoding" },
    
    /* Performance Monitor Bitfields */ 
    { BO_V7A_PMCCNTR_CCNT, MS_IOCTL_PMCCNTR, NS_PRIVILEGE_LEVEL_1, 0, 32, "CCNT", "perfmon", "PMCCNTR", "Cycle count" },
    
    { BO_V7A_PMCEID0_00, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 0, 1, "0x00", "perfmon", "PMCEID0", "Software Increment" },
    { BO_V7A_PMCEID0_01, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 1, 1, "0x01", "perfmon", "PMCEID0", "Level 1 instruction cache refill" },
    { BO_V7A_PMCEID0_02, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 2, 1, "0x02", "perfmon", "PMCEID0", "Level 1 instruction TLB refill" },
    { BO_V7A_PMCEID0_03, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 3, 1, "0x03", "perfmon", "PMCEID0", "Level 1 data cache refill" },
    { BO_V7A_PMCEID0_04, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 4, 1, "0x04", "perfmon", "PMCEID0", "Level 1 data cache access" },
    { BO_V7A_PMCEID0_05, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 5, 1, "0x05", "perfmon", "PMCEID0", "Level 1 data TLB refill" },
    { BO_V7A_PMCEID0_06, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 6, 1, "0x06", "perfmon", "PMCEID0", "Load" },
    { BO_V7A_PMCEID0_07, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 7, 1, "0x07", "perfmon", "PMCEID0", "Store" },
    { BO_V7A_PMCEID0_08, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 8, 1, "0x08", "perfmon", "PMCEID0", "Instruction architecturally executed" },
    { BO_V7A_PMCEID0_09, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 9, 1, "0x09", "perfmon", "PMCEID0", "Exception taken" },
    { BO_V7A_PMCEID0_10, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 10, 1, "0x0A", "perfmon", "PMCEID0", "Exception return" },
    { BO_V7A_PMCEID0_11, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 11, 1, "0x0B", "perfmon", "PMCEID0", "Write to CONTEXTIDR" },
    { BO_V7A_PMCEID0_12, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 12, 1, "0x0C", "perfmon", "PMCEID0", "Software change of the PC" },
    { BO_V7A_PMCEID0_13, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 13, 1, "0x0D", "perfmon", "PMCEID0", "Immediate Branch" },
    { BO_V7A_PMCEID0_14, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 14, 1, "0x0E", "perfmon", "PMCEID0", "Procedure return" },
    { BO_V7A_PMCEID0_15, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 15, 1, "0x0F", "perfmon", "PMCEID0", "Unaligned load or store" },
    { BO_V7A_PMCEID0_16, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 16, 1, "0x10", "perfmon", "PMCEID0", "Speculative execution" },
    { BO_V7A_PMCEID0_17, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 17, 1, "0x11", "perfmon", "PMCEID0", "Cycle" },
    { BO_V7A_PMCEID0_18, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 18, 1, "0x12", "perfmon", "PMCEID0", "Predictable branch speculatively executed" },
    { BO_V7A_PMCEID0_19, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 19, 1, "0x13", "perfmon", "PMCEID0", "Data memory access" },
    { BO_V7A_PMCEID0_20, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 20, 1, "0x14", "perfmon", "PMCEID0", "Level 1 instruction cache access" },
    { BO_V7A_PMCEID0_21, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 21, 1, "0x15", "perfmon", "PMCEID0", "Level 1 data cache write-back" },
    { BO_V7A_PMCEID0_22, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 22, 1, "0x16", "perfmon", "PMCEID0", "Level 2 data cache access" },
    { BO_V7A_PMCEID0_23, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 23, 1, "0x17", "perfmon", "PMCEID0", "Level 2 data cache refill" },
    { BO_V7A_PMCEID0_24, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 24, 1, "0x18", "perfmon", "PMCEID0", "Level 2 data cache write-back" },
    { BO_V7A_PMCEID0_25, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 25, 1, "0x19", "perfmon", "PMCEID0", "Bus access" },
    { BO_V7A_PMCEID0_26, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 26, 1, "0x1A", "perfmon", "PMCEID0", "Local memory error" },
    { BO_V7A_PMCEID0_27, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 27, 1, "0x1B", "perfmon", "PMCEID0", "Instruction speculatively executed" },
    { BO_V7A_PMCEID0_28, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 28, 1, "0x1C", "perfmon", "PMCEID0", "Write to TTBR" },
    { BO_V7A_PMCEID0_29, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 29, 1, "0x1D", "perfmon", "PMCEID0", "Bus cycle" },
    { BO_V7A_PMCEID0_30, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 30, 1, "0x1E", "perfmon", "PMCEID0", "Reserved" },
    { BO_V7A_PMCEID0_31, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 31, 1, "0x1F", "perfmon", "PMCEID0", "Reserved" },
    
    { BO_V7A_PMCEID1_IMPLEMENTATION, MS_IOCTL_PMCEID0, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMCEID1", "Implementation Defined" },
    
    { BO_V7A_PMCNTENCLR_IMPLEMENTATION, MS_IOCTL_PMCNTENCLR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMCNTENCLR", "Implementation Defined" },
    
    { BO_V7A_PMCNTENSET_IMPLEMENTATION, MS_IOCTL_PMCNTENSET, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMCNTENSET", "Implementation Defined" },
    
    { BO_V7A_PMINTENSET_IMPLEMENTATION, MS_IOCTL_PMINTENSET, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMINTENSET", "Implementation Defined" },
    
    { BO_V7A_PMINTENCLR_IMPLEMENTATION, MS_IOCTL_PMINTENCLR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMINTENCLR", "Implementation Defined" },
    
    { BO_V7A_PMOVSR_IMPLEMENTATION, MS_IOCTL_PMOVSR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMOVSR", "Implementation Defined" },
    
    { BO_V7A_PMOVSSET_IMPLEMENTATION, MS_IOCTL_PMOVSSET, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMOVSSET", "Implementation Defined" },
        
    { BO_V7A_PMSELR_SEL, MS_IOCTL_PMSELR, NS_PRIVILEGE_LEVEL_1, 0, 5, "SELR", "perfmon", "PMSELR", "Selects event counter" },
    { BO_V7A_PMSELR_RESERVED, MS_IOCTL_PMSELR, NS_PRIVILEGE_LEVEL_1, 5, 27, "Reserved", "perfmon", "PMSELR", "Reserved" },

    { BO_V7A_PMSWINC_IMPLEMENTATION, MS_IOCTL_PMSWINC, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "perfmon", "PMSWINC", "Implementation Defined" },
    
    { BO_V7A_PMUSERENR_EN, MS_IOCTL_PMUSERENR, NS_PRIVILEGE_LEVEL_1, 0, 1, "EN", "perfmon", "PMUSERENR", "User mode access enable bit" },
    { BO_V7A_PMUSERENR_RESERVED, MS_IOCTL_PMUSERENR, NS_PRIVILEGE_LEVEL_1, 1, 31, "Reserved", "perfmon", "PMUSERENR", "Reserved" },
    
    { BO_V7A_PMXEVCNTR_PMNX, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 0, 32, "PMNx", "perfmon", "PMXEVCNTR", "Value of selected event counter" },
    
    { BO_V7A_PMXEVTYPER_EVTCOUNT, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 0, 8, "evtCount", "perfmon", "PMXEVTYPER", "Event to count" },
    { BO_V7A_PMXEVTYPER_RESERVED, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 8, 19, "Reserved", "perfmon", "PMXEVTYPER", "Reserved" },
    { BO_V7A_PMXEVTYPER_NSH, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 27, 1, "NSH", "perfmon", "PMXEVTYPER", "Non-secure PL2 enable" },
    { BO_V7A_PMXEVTYPER_NSU, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 28, 1, "NSU", "perfmon", "PMXEVTYPER", "Non-secure unprivileged control bit" },
    { BO_V7A_PMXEVTYPER_NSK, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 29, 1, "NSK", "perfmon", "PMXEVTYPER", "Non-secure PL1 control bit" },
    { BO_V7A_PMXEVTYPER_U, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 30, 1, "U", "perfmon", "PMXEVTYPER", "Unprivileged execution filtering bit" },
    { BO_V7A_PMXEVTYPER_P, MS_IOCTL_PMXEVCNTR, NS_PRIVILEGE_LEVEL_1, 31, 1, "P", "perfmon", "PMXEVTYPER", "Privileged execution filtering bit" },
    
    { BO_V7A_PMCR_E, MS_IOCTL_PMCR, NS_ALL, 0, 1, "E", "perfmon", "PMCR", "All counters enable" },
    { BO_V7A_PMCR_P, MS_IOCTL_PMCR, NS_ALL, 1, 1, "P", "perfmon", "PMCR", "Event counter reset" },
    { BO_V7A_PMCR_C, MS_IOCTL_PMCR, NS_ALL, 2, 1, "C", "perfmon", "PMCR", "Cycle counter reset" },
    { BO_V7A_PMCR_D, MS_IOCTL_PMCR, NS_ALL, 3, 1, "D", "perfmon", "PMCR", "Cycle counter clock divider" },
    { BO_V7A_PMCR_X, MS_IOCTL_PMCR, NS_ALL, 4, 1, "X", "perfmon", "PMCR", "Export enable" },
    { BO_V7A_PMCR_DP, MS_IOCTL_PMCR, NS_ALL, 5, 1, "DP", "perfmon", "PMCR", "Disable PMCCNTR when event counting is prohibited" },
    { BO_V7A_PMCR_RESERVED, MS_IOCTL_PMCR, NS_ALL, 6, 5, "Rerverced", "perfmon", "PMCR", "Reserved" },
    { BO_V7A_PMCR_N, MS_IOCTL_PMCR, NS_ALL, 11, 5, "N", "perfmon", "PMCR", "Number of event counters" },
    { BO_V7A_PMCR_IDCODE, MS_IOCTL_PMCR, NS_ALL, 16, 8, "IDCODE", "perfmon", "PMCR", "Identification Code" },
    { BO_V7A_PMCR_IMP, MS_IOCTL_PMCR, NS_ALL, 24, 8, "Implementation Defined", "perfmon", "PMCR", "Implementer Code" },
    
    /* "other" handling bitfields */
    { BO_V7A_ACTLR_IMPLEMENTATION, MS_IOCTL_ACTLR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "other", "ACTLR", "Implementation Defined" },
    
    { BO_V7A_CPACR_CP0, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 0, 2, "CP0", "other", "CPACR", "Coprocessor 0" },
    { BO_V7A_CPACR_CP1, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 2, 2, "CP1", "other", "CPACR", "Coprocessor 1" },
    { BO_V7A_CPACR_CP2, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 4, 2, "CP2", "other", "CPACR", "Coprocessor 2" },
    { BO_V7A_CPACR_CP3, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 6, 2, "CP3", "other", "CPACR", "Coprocessor 3" },
    { BO_V7A_CPACR_CP4, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 8, 2, "CP4", "other", "CPACR", "Coprocessor 4" },
    { BO_V7A_CPACR_CP5, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 10, 2, "CP5", "other", "CPACR", "Coprocessor 5" },
    { BO_V7A_CPACR_CP6, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 12, 2, "CP6", "other", "CPACR", "Coprocessor 6" },
    { BO_V7A_CPACR_CP7, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 14, 2, "CP7", "other", "CPACR", "Coprocessor 7" },
    { BO_V7A_CPACR_CP8, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 16, 2, "CP8", "other", "CPACR", "Coprocessor 8" },
    { BO_V7A_CPACR_CP9, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 18, 2, "CP9", "other", "CPACR", "Coprocessor 9" },
    { BO_V7A_CPACR_CP10, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 20, 2, "CP10", "other", "CPACR", "Coprocessor 10" },
    { BO_V7A_CPACR_CP11, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 22, 2, "CP11", "other", "CPACR", "Coprocessor 11" },
    { BO_V7A_CPACR_CP12, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 24, 2, "CP12", "other", "CPACR", "Coprocessor 12" },
    { BO_V7A_CPACR_CP13, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 26, 2, "CP13", "other", "CPACR", "Coprocessor 13" },
    { BO_V7A_CPACR_TRCDIS, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 28, 1, "TRCDIS", "other", "CPACR", "Disable CP14 access to trace registers" },
    { BO_V7A_CPACR_RESERVED, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 29, 1, "Reserved", "other", "CPACR", "Reserved" },
    { BO_V7A_CPACR_D32DIS, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 30, 1, "D32DIS", "other", "CPACR", "Disable use of D16-D32 of FP Extension register file" },
    { BO_V7A_CPACR_ASEDIS, MS_IOCTL_CPACR, NS_PRIVILEGE_LEVEL_1, 31, 1, "ASEDIS", "other", "CPACR", "Disable Advanced SIMD functionality" },
    
    { BO_V7A_FCSEIDR_RESERVED, MS_IOCTL_FCSEIDR, NS_PRIVILEGE_LEVEL_1, 0, 25, "Reserved", "other", "FCSEIDR", "Reserved" },
    { BO_V7A_FCSEIDR_PID, MS_IOCTL_FCSEIDR, NS_PRIVILEGE_LEVEL_1, 25, 8, "PID", "other", "FCSEIDR", "Current Process ID for FCSE" },   
        
    /* Fault handling bitfields */  
    { BO_V7A_IFAR_VA, MS_IOCTL_IFAR, NS_PRIVILEGE_LEVEL_1, 0, 32, "VA", "fault", "IFAR", "VA of faulting address of synchronous Prefetch Abort exception" },
    
    { BO_V7A_IFSR_FS_3_0, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 0, 4, "FS_3_0", "fault", "IFSR", "Fault status bit" },
    { BO_V7A_IFSR_RESERVED_01, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 4, 5, "Reserved", "fault", "IFSR", "Reserved" },
    { BO_V7A_IFSR_LPAE, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 9, 1, "LPAE", "fault", "IFSR", "Descriptor table format on exception" },
    { BO_V7A_IFSR_FS_4, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 10, 1, "FS_4", "fault", "IFSR", "Fault status bit" },
    { BO_V7A_IFSR_RESERVED_02, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 11, 1, "Reserved", "fault", "IFSR", "Reserved" },
    { BO_V7A_IFSR_EXT, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 12, 1, "ExT", "fault", "IFSR", "External abort type" },
    { BO_V7A_IFSR_RESERVED_03, MS_IOCTL_IFSR, NS_PRIVILEGE_LEVEL_1, 13, 19, "Reserved", "fault", "IFSR", "Reserved" },
    
    { BO_V7A_ADFSR_IMPLEMENTATION, MS_IOCTL_ADFSR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "fault", "ADFSR", "Implementation Defined" },
    
    { BO_V7A_AIFSR_IMPLEMENTATION, MS_IOCTL_AIFSR, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "fault", "AIFSR", "Implementation Defined" },

    { BO_V7A_DFAR_VA, MS_IOCTL_DFAR, NS_PRIVILEGE_LEVEL_1, 0, 32, "VA", "fault", "DFAR", "VA of faulting address of synchronous Data Abort exception" },
    
    { BO_V7A_DFSR_FS_3_0, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 0, 4, "FS_3_0", "fault", "DFSR", "Fault status bit" },
    { BO_V7A_DFSR_DOMAIN, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 4, 4, "Domain", "fault", "DFSR", "The domain of the fault address" },
    { BO_V7A_DFSR_RESERVED_01, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 8, 1, "Reserved", "fault", "DFSR", "Reserved" },
    { BO_V7A_DFSR_LPAE, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 9, 1, "LPAE", "fault", "DFSR", "Indicates short-descriptor table format on exception" },
    { BO_V7A_DFSR_FS_4, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 10, 1, "FS_4", "fault", "DFSR", "Fault status bit" },
    { BO_V7A_DFSR_WNR, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 11, 1, "WnR", "fault", "DFSR", "Abort caused by read or write" },
    { BO_V7A_DFSR_EXT, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 12, 1, "ExT", "fault", "DFSR", "External abort type" },
    { BO_V7A_DFSR_CM, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 13, 1, "CM", "fault", "DFSR", "Cache maintenance fault" },
    { BO_V7A_DFSR_RESERVED_02, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 14, 18, "Reserved", "fault", "DFSR", "Reserved" },
    
    /* Jazelle */
    { BO_V7A_JIDR_IMPLEMENTATION, MS_IOCTL_JIDR, NS_PRIVILEGE_LEVEL_1, 0, 12, "ImplementationdDefined", "jazelle", "JIDR", "Subarchitecture defined" },
    { BO_V7A_JIDR_SUBARCH, MS_IOCTL_JIDR, NS_PRIVILEGE_LEVEL_1, 12, 8, "Subarchitecture", "jazelle", "JIDR", "Subarchitecture code" },
    { BO_V7A_JIDR_IMPL, MS_IOCTL_JIDR, NS_PRIVILEGE_LEVEL_1, 20, 8, "Implementer", "jazelle", "JIDR", "Implementer code" },
    { BO_V7A_JIDR_ARCH, MS_IOCTL_JIDR, NS_PRIVILEGE_LEVEL_1, 28, 4, "Architecture", "jazelle", "JIDR", "Architecture code" },
    
    { BO_V7A_JMCR_JE, MS_IOCTL_JMCR, NS_PRIVILEGE_LEVEL_1, 0, 1, "JE", "jazelle", "JMCR", "Jazelle extensions enable" },
    { BO_V7A_JMCR_IMPLEMENTATION, MS_IOCTL_JMCR, NS_PRIVILEGE_LEVEL_1, 1, 31, "Implementation defined", "jazelle", "JMCR", "Implementation defined" },

    { BO_V7A_JOSCR_CD, MS_IOCTL_JOSCR, NS_PRIVILEGE_LEVEL_1, 0, 1, "CD", "jazelle", "JOSCR", "Disable user mode access to JIDR and configuration registers" },
    { BO_V7A_JOSCR_CV, MS_IOCTL_JOSCR, NS_PRIVILEGE_LEVEL_1, 1, 1, "CV", "jazelle", "JOSCR", "Instruct EJVM to rewrite configuration in registers" },
    { BO_V7A_JOSCR_RESERVED, MS_IOCTL_JOSCR, NS_PRIVILEGE_LEVEL_1, 2, 30, "Reserved", "jazelle", "JOSCR", "Reserved" },
    
    /* Thumb */
    { BO_V7A_TEECR_XED, MS_IOCTL_TEECR, NS_ALL, 0, 1, "XED", "thumb", "TEECR", "Unprivileged Execution Environment Disable" },
    { BO_V7A_TEECR_RESERVED, MS_IOCTL_TEECR, NS_ALL, 1, 31, "Reserved", "thumb", "TEECR", "Reserved" },
    
    { BO_V7A_TEEHBR_RESERVED, MS_IOCTL_TEEHBR, NS_ALL, 0, 2, "Reserved", "thumb", "TEEHBR", "Reserved" },
    { BO_V7A_TEEHBR_HANDLERBASE, MS_IOCTL_TEEHBR, NS_ALL, 2, 30, "HandlerBase", "thumb", "TEEHBR", "Address of ThumbEE handlers" },
    
    /* Misc */
    { BO_V7A_TPIDRPRW_IMPLEMENTATION, MS_IOCTL_TPIDRPRW, NS_PRIVILEGE_LEVEL_1, 0, 32, "Implementation Defined", "misc", "TPIDRPRW", "PL1 Thread ID Storage" },
    
    { BO_V7A_TPIDRURO_IMPLEMENTATION, MS_IOCTL_TPIDRURO, NS_PRIVILEGE_LEVEL_0, 0, 32, "Implementation Defined", "misc", "TPIDRURO", "PL0 Thread ID Storage" },
    
    { BO_V7A_TPIDRURW_IMPLEMENTATION, MS_IOCTL_TPIDRURW, ALL_NS_S, 0, 32, "Implementation Defined", "misc", "TPIDRURW", "PL0 Thread ID Storage" },
    
    /* Address Translation */
    { BO_V7A_PAR_F, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 0, 1, "F", "addrtrans", "PAR", "Conversion status" },
    { BO_V7A_PAR_SS, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 1, 1, "SS", "addrtrans", "PAR", "Result is a supersection" },
    { BO_V7A_PAR_OUTER_1_0, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 2, 1, "Outer_1_0", "addrtrans", "PAR", "Outer memory attributes" },
    { BO_V7A_PAR_INNER_2_0, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 4, 3, "Inner_2_0", "addrtrans", "PAR", "Inner memory attributes" },
    { BO_V7A_PAR_SH, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 7, 1, "Shareable attribute", "addrtrans", "PAR", "Physical memory is shareable" },
    { BO_V7A_PAR_IMPLEMENTATION, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 8, 1, "Implementation Defined", "addrtrans", "PAR", "Implementation Defined" },
    { BO_V7A_PAR_NS, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 9, 1, "Non-secure", "addrtrans", "PAR", "NS bit from secure state" },
    { BO_V7A_PAR_NOS, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 10, 1, "NOS", "addrtrans", "PAR", "Not outer shareable bit" },
    { BO_V7A_PAR_LPAE, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 11, 1, "LPAE", "addrtrans", "PAR", "Implementation includes LPAE" },
    { BO_V7A_PAR_PA, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 12, 20, "PA", "addrtrans", "PAR", "Physical address" },
    
    /* Program Status Register */
    { BO_V7A_APSR_RESERVED_01, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 0, 16, "Reserved", "psr", "APSR", "Reserved" },
    { BO_V7A_APSR_GE, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 16, 4, "GE", "psr", "APSR", "Greater than or equal to" },
    { BO_V7A_APSR_RESERVED_02, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 20, 4, "Reserved", "psr", "APSR", "Reserved" },
    { BO_V7A_APSR_RESERVED_03, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 24, 3, "Reserved", "psr", "APSR", "Reserved" },
    { BO_V7A_APSR_Q, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 27, 1, "Q", "psr", "APSR", "Overflow or saturation" },
    { BO_V7A_APSR_V, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 28, 1, "V", "psr", "APSR", "Overflow condition" },
    { BO_V7A_APSR_C, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 29, 1, "C", "psr", "APSR", "Carry condition" },
    { BO_V7A_APSR_Z, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 30, 1, "Z", "psr", "APSR", "Zero condition" },
    { BO_V7A_APSR_N, MS_IOCTL_APSR, NS_PRIVILEGE_LEVEL_0 | NS_PRIVILEGE_LEVEL_1, 31, 1, "N", "psr", "APSR", "Negative condition" },
    
    { BO_V7A_CPSR_M, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 0, 5, "M", "psr", "CPSR", "Current mode of processor" },
    { BO_V7A_CPSR_T, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 5, 1, "T", "psr", "CPSR", "Thumb execution state" },
    { BO_V7A_CPSR_F, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 6, 1, "F", "psr", "CPSR", "FIQ mask" },
    { BO_V7A_CPSR_I, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 7, 1, "I", "psr", "CPSR", "IRQ mask" },
    { BO_V7A_CPSR_A, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 8, 1, "A", "psr", "CPSR", "Asynchronous abort mask" },
    { BO_V7A_CPSR_E, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 9, 1, "E", "psr", "CPSR", "Endianess" },
    { BO_V7A_CPSR_IT_7_2, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 10, 6, "IT", "psr", "CPSR", "If-then execution state [7:2]" },
    { BO_V7A_CPSR_GE, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 16, 4, "GE", "psr", "CPSR", "Greater than or equal to" },
    { BO_V7A_CPSR_RESERVED, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 20, 4, "Reserved", "psr", "CPSR", "Reserved" },
    { BO_V7A_CPSR_J, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 24, 1, "J", "psr", "CPSR", "Jazelle bit" },
    { BO_V7A_CPSR_IT_1_0, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_1, 25, 2, "IT", "psr", "CPSR", "If-then execution state [1:0]" },
    { BO_V7A_CPSR_Q, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 27, 1, "Q", "psr", "CPSR", "Cumulative saturation bit" },
    { BO_V7A_CPSR_V, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 28, 1, "V", "psr", "CPSR", "Overflow condition" },
    { BO_V7A_CPSR_C, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 29, 1, "C", "psr", "CPSR", "Carry condition" },
    { BO_V7A_CPSR_Z, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 30, 1, "Z", "psr", "CPSR", "Zero condition" },
    { BO_V7A_CPSR_N, MS_IOCTL_CPSR, NS_PRIVILEGE_LEVEL_0, 31, 1, "N", "psr", "CPSR", "Negative condition" },

};

int
return_bitfield_armv7a_size(void)
{
    return (sizeof(bitfield_armv7a_table) / sizeof(bitfield_info));
}
