#include <stdio.h>
#include <sys/ioctl.h>

#include "maplesyrup.h"
#include "parse.h"
#include "bitfield_cortex-a53.h"

bitfield_info bitfield_cortex_a53_table[] =
{   
    { BO_A53_L2CTLR_OUTPUTLATENCY, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 0, 1, "OUTPUTLATENCY", "impl_def", "L2CTLR", "L2 Data RAM output latency" },
    { BO_A53_L2CTLR_RESERVED_01, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 1, 4, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A53_L2CTLR_INPUTLATENCY, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "INPUTLATENCY", "impl_def", "L2CTLR", "L2 Data RAM input latency" },
    { BO_A53_L2CTLR_RESERVED_02, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 6, 15, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A53_L2CTLR_SCUL2, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "SCUL2", "impl_def", "L2CTLR", "SCU-L2 Cache Protection" },
    { BO_A53_L2CTLR_CPU, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 22, 1, "CPU", "impl_def", "L2CTLR", "CPU Cache Protection" },
    { BO_A53_L2CTLR_RESERVED_03, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 23, 1, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A53_L2CTLR_CORES, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 24, 2, "CORES", "impl_def", "L2CTLR", "Number of cores" },
    { BO_A53_L2CTLR_RESERVED_04, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 26, 6, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    
    { BO_A53_L2ECTLR_DYNRET, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 0, 3, "DYNRET", "impl_def", "L2ECTLR", "L2 dynamic retention control" },
    { BO_A53_L2ECTLR_RESERVED_01, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 3, 26, "Reserved", "impl_def", "L2ECTLR", "Reserved" },
    { BO_A53_L2ECTLR_ASYNCERR, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 29, 1, "ASYNCERR", "impl_def", "L2ECTLR", "ACI or AMBA 5 CHI asynchronous error" },
    { BO_A53_L2ECTLR_IASYNCERR, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 30, 1, "IASYNCERR", "impl_def", "L2ECTLR", "L2 internal asynchronous error" },
    { BO_A53_L2ECTLR_RESERVED_02, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 31, 1, "IASYNCERR", "impl_def", "L2ECTLR", "L2 internal asynchronous error" },
    
    { BO_A53_L2ACTLR_RESERVED_01, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 0, 3, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A53_L2ACTLR_DCEPTE, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 3, 1, "DCEPTE", "impl_def", "L2ACTLR", "Disable clean/evict push to external" },
    { BO_A53_L2ACTLR_RESERVED_02, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 4, 10, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A53_L2ACTLR_EUEWD, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 14, 1, "EUEWD", "impl_def", "L2ACTLR", "Enable UniqueClean evictions with data" },
    { BO_A53_L2ACTLR_RESERVED_03, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 15, 9, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A53_L2ACTLR_L2TEIEN, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "L2TEIEN", "impl_def", "L2ACTLR", "L2 cache tag RAM error injection enable" },
    { BO_A53_L2ACTLR_RESERVED_04, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 25, 4, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A53_L2ACTLR_L2DEIEN, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 29, 1, "L2DEIEN", "impl_def", "L2ACTLR", "L2 cache data RAM error injection enable" },
    { BO_A53_L2ACTLR_L2VC, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 30, 2, "L2VC", "impl_def", "L2ACTLR", "L2 Victim Control" },
    
    { BO_A53_PAR_F, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 0, 1, "D", "addrtrans", "PAR", "Indicates successful conversion" },
    { BO_A53_PAR_RESERVED_01, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 1, 6, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A53_PAR_SHA, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 7, 2, "SHA", "addrtrans", "PAR", "Shareability attribute" },
    { BO_A53_PAR_NS, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 9, 1, "NS", "addrtrans", "PAR", "Non-secure" },
    { BO_A53_PAR_RESERVED_02, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 10, 1, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A53_PAR_RESERVED_03, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 11, 1, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A53_PAR_PA, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 12, 36, "PA", "addrtrans", "PAR", "Physical address" },
    { BO_A53_PAR_RESERVED_04, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 48, 8, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A53_PAR_ATTRL, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 56, 4, "AttrL", "addrtrans", "PAR", "Defines device memory and inner cacheability" },
    { BO_A53_PAR_ATTRH, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 60, 4, "AttrH", "addrtrans", "PAR", "Defined normal and device memory and outer cacheability" },

    { BO_A53_CPUACTLR_RESERVED_01, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 0, 6, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A53_CPUACTLR_L1DEIEN, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "L1DEIEN", "impl_def", "CPUACTLR", "L1 D-cache data RAM error injection enable" },
    { BO_A53_CPUACTLR_RESERVED_02, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 7, 3, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A53_CPUACTLR_DODMBS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 10, 1, "DODMBS", "impl_def", "CPUACTLR", "Disable optimized Data Memory Barrier behavior" },
    { BO_A53_CPUACTLR_RESERVED_03, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 11, 2, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A53_CPUACTLR_L1PCTL, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 13, 3, "L1PCTL", "impl_def", "CPUACTLR", "L1 Data prefetch control" },
    { BO_A53_CPUACTLR_RESERVED_04, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 16, 1, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A53_CPUACTLR_STRIDE, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 17, 1, "STRIDE", "impl_def", "CPUACTLR", "Configure the sequence length that triggers data prefetch streams" },
    { BO_A53_CPUACTLR_DSTDIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 18, 1, "DSTDIS", "impl_def", "CPUACTLR", "Enable device split throttle" },
    { BO_A53_CPUACTLR_NPFSTRM, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 19, 2, "NPFSTRM", "impl_def", "CPUACTLR", "Number of independent data prefetch streams" },
    { BO_A53_CPUACTLR_IFUTHDIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "IFUTHDIS", "impl_def", "CPUACTLR", "IFU fetch throttle disabled" },
    { BO_A53_CPUACTLR_STBPFDIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 22, 1, "STBPFDIS", "impl_def", "CPUACTLR", "Disable prefetch streams initiated from STB accesses" },
    { BO_A53_CPUACTLR_STBPFRS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 23, 1, "STBPFDIS", "impl_def", "CPUACTLR", "Disable ReadUnique request for prefetch streams initiated by STB accesses" },
    { BO_A53_CPUACTLR_DTAH, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "DTAH", "impl_def", "CPUACTLR", "Disable transient allocation hint" },
    { BO_A53_CPUACTLR_L1RADIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 25, 2, "L1RADIS", "impl_def", "CPUACTLR", "Write streaming no-L1-allocate threshold" },
    { BO_A53_CPUACTLR_RADIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 27, 2, "RADIS", "impl_def", "CPUACTLR", "Write streaming no-allocate threshold" },
    { BO_A53_CPUACTLR_DIDIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 29, 1, "DIDIS", "impl_def", "CPUACTLR", "Disable dual issue" },
    { BO_A53_CPUACTLR_FPDIDIS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 30, 1, "FPDIDIS", "impl_def", "CPUACTLR", "Disable floating-point dual issue" },
    { BO_A53_CPUACTLR_RESERVED_05, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 31, 13, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A53_CPUACTLR_ENDCCASCI, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 44, 1, "ENDCCASCI", "impl_def", "CPUACTLR", "Enable data cache clean as data cache clean/invalidate" },
    { BO_A53_CPUACTLR_RESERVED_06, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 45, 19, "Reserved", "impl_def", "CPUACTLR", "Reserved" },  
    
    { BO_A53_CPUECTLR_CPURETCTL, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 0, 3, "CPURETCTL", "impl_def", "CPUECTLR", "CPU retention control" },    
    { BO_A53_CPUECTLR_FPRETCTL, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 3, 3, "FPRETCTL", "impl_def", "CPUECTLR", "Advanced SIMD and Floating-point retention control" }, 
    { BO_A53_CPUECTLR_SMPEN, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "SMPEN", "impl_def", "CPUECTLR", "Enable hardware management of data coherency with other cores in the cluster" }, 
    { BO_A53_CPUECTLR_RESERVED, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 7, 57, "Reserved", "impl_def", "CPUECTLR", "Reserved" },
    
    { BO_A53_CPUMERRSR_RAMADDR, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 0, 12, "RAMADDR", "impl_def", "CPUMERRSR", "Indicates the index address of the first memory error" },    
    { BO_A53_CPUMERRSR_RESERVED_01, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 12, 6, "Reserved", "impl_def", "CPUMERRSR", "Reserved" },    
    { BO_A53_CPUMERRSR_CPUIDWAY, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 18, 3, "CPUIDWAY", "impl_def", "CPUMERRSR", "Indicates the RAM where the first memory error occurred" },    
    { BO_A53_CPUMERRSR_RESERVED_02, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 21, 3, "Reserved", "impl_def", "CPUMERRSR", "Reserved" },    
    { BO_A53_CPUMERRSR_RAMID, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 24, 7, "RAMID", "impl_def", "CPUMERRSR", "Ram Identifier" },
    { BO_A53_CPUMERRSR_VALID, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 31, 1, "Valid", "impl_def", "CPUMERRSR", "Valid bit. Set to 1 on first memory error" },
    { BO_A53_CPUMERRSR_REC, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 32, 8, "REC", "impl_def", "CPUMERRSR", "Repeat memory error count when valid bit is set" },
    { BO_A53_CPUMERRSR_OEC, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 40, 8, "OEC", "impl_def", "CPUMERRSR", "Other memory error count when valid bit is set" },
    { BO_A53_CPUMERRSR_RESERVED_03, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 48, 15, "Reserved", "impl_def", "CPUMERRSR", "Reserved" },
    { BO_A53_CPUMERRSR_FATAL, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 63, 1, "Fatal", "impl_def", "CPUMERRSR", "Fatal bit. Set to 1 on first memory error that cased data abort" },

    { BO_A53_L2MERRSR_RESERVED_01, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 0, 3, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A53_L2MERRSR_RAMADDR, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 3, 14, "RAMADDR", "impl_def", "L2MERRSR", "Indicates the index address of the first memory error" },   
    { BO_A53_L2MERRSR_RESERVED_02, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 17, 1, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A53_L2MERRSR_CPUIDWAY, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 18, 4, "CPUIDWAY", "impl_def", "L2MERRSR", "Indicates the RAM where the first memory error occurred" },   
    { BO_A53_L2MERRSR_RESERVED_03, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 22, 2, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A53_L2MERRSR_RAMID, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 24, 7, "RAMID", "impl_def", "L2MERRSR", "Indicates the RAM where the first memory error occurred" }, 
    { BO_A53_L2MERRSR_VALID, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 31, 1, "VALID", "impl_def", "L2MERRSR", "Valid bit. Set to 1 on first memory error" },
    { BO_A53_L2MERRSR_REC, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 32, 8, "REC", "impl_def", "L2MERRSR", "Repeat memory error count when valid bit is set" },
    { BO_A53_L2MERRSR_OEC, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 40, 8, "OEC", "impl_def", "L2MERRSR", "Other memory error count when valid bit is set" },
    { BO_A53_L2MERRSR_RESERVED_04, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 48, 15, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A53_L2MERRSR_FATAL, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 63, 1, "Fatal", "impl_def", "L2MERRSR", "Fatal bit. Set to 1 on first memory error that cased data abort" },

    { BO_A53_CBAR_RESERVED_01, MS_IOCTL_CBAR, NS_PRIVILEGE_LEVEL_1, 0, 18, "Reserved", "impl_def", "CBAR", "Reserved" },
    { BO_A53_CBAR_PERIPHBASE_39_18, MS_IOCTL_CBAR, NS_PRIVILEGE_LEVEL_1, 18, 32, "PERIPHBASE_39_18", "impl_def", "CBAR", "Reset base address of memory-mapped GIC CPU interface registers" },
    { BO_A53_CBAR_RESERVED_02, MS_IOCTL_CBAR, NS_PRIVILEGE_LEVEL_1, 40, 24, "Reserved", "impl_def", "CBAR", "Reserved" },

    { BO_A53_SCTLR_EL1_M, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 0, 1, "M", "virtmem", "SCTLR", "MMU Enable" },
    { BO_A53_SCTLR_EL1_A, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 1, 1, "A", "virtmem", "SCTLR", "Alignment check enable" },
    { BO_A53_SCTLR_EL1_C, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 2, 1, "C", "virtmem", "SCTLR", "Cache enable" },
    { BO_A53_SCTLR_EL1_SA, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 3, 1, "SA", "virtmem", "SCTLR", "Stack alignment check enable" },
    { BO_A53_SCTLR_EL1_SA0, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 4, 1, "SA0", "virtmem", "SCTLR", "Stack alignment check enable for EL0" },
    { BO_A53_SCTLR_EL1_CP15BEN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "CP15BEN", "virtmem", "SCTLR", "CP15 barrier enable" },
    { BO_A53_SCTLR_EL1_THEE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "THEE", "virtmem", "SCTLR", "T32EE not implemented" },
    { BO_A53_SCTLR_EL1_ITD, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 7, 1, "ITD", "virtmem", "SCTLR", "Disables some uses of IT instructions at EL0 using AArch32" },
    { BO_A53_SCTLR_EL1_SED, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 8, 1, "SED", "virtmem", "SCTLR", "Disables the SETEND instruction at EL0 using AArch32" },
    { BO_A53_SCTLR_EL1_UMA, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 9, 1, "UMA", "virtmem", "SCTLR", "Traps EL0 execution of MSR and MRS instructions that access PSTATE" },
    { BO_A53_SCTLR_EL1_RESERVED_01, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 10, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_RESERVED_02, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 11, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_I, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 12, 1, "I", "virtmem", "SCTLR", "Instruction access Cacheability control" },
    { BO_A53_SCTLR_EL1_RESERVED_03, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 13, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_DZE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 14, 1, "DZE", "virtmem", "SCTLR", "Traps EL0 execution of DC ZVA instructions to EL1" },
    { BO_A53_SCTLR_EL1_UCT, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 15, 1, "UCT", "virtmem", "SCTLR", "Traps EL0 access to the CTR_EL0 register to EL1" },
    { BO_A53_SCTLR_EL1_NTWI, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 16, 1, "NTWI", "virtmem", "SCTLR", "Traps EL0 execution of WFI instructions to EL1" },
    { BO_A53_SCTLR_EL1_RESERVED_04, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 17, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_NTWE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 18, 1, "NTWE", "virtmem", "SCTLR", "Traps EL0 execution of WFE instructions to EL1" },
    { BO_A53_SCTLR_EL1_WXN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 19, 1, "WXN", "virtmem", "SCTLR", "Write permission implies XN (Execute Never) at EL0/1" },
    { BO_A53_SCTLR_EL1_RESERVED_05, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 20, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_RESERVED_06, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_RESERVED_07, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 22, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_E0E, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "E0E", "virtmem", "SCTLR", "Endianess of data access at EL0" },
    { BO_A53_SCTLR_EL1_EE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 25, 1, "EE", "virtmem", "SCTLR", "Endianess of data at EL1 and translation table walk" },
    { BO_A53_SCTLR_EL1_UCI, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 26, 1, "UCI", "virtmem", "SCTLR", "Traps EL0 cache maintenance instructions to EL1" },
    { BO_A53_SCTLR_EL1_RESERVED_08, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 27, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_RESERVED_09, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 28, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A53_SCTLR_EL1_RESERVED_10, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 30, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    
    { BO_A53_ESR_ISS, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 0, 24, "ISS", "fault", "ESR", "Syndrome information" },
    { BO_A53_ESR_ISSVALID, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 24, 1, "ISS Valid", "fault", "ESR", "Syndrome information" },
    { BO_A53_ESR_IL, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 25, 1, "IL", "fault", "ESR", "Instruction length for synchronous exception" },
    { BO_A53_ESR_EC, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 26, 5, "EC", "fault", "ESR", "Exception reason class" },
    
};

int
return_bitfield_cortex_a53_size(void)
{
    return (sizeof(bitfield_cortex_a53_table) / sizeof(bitfield_info));
}
