#ifndef _BITFIELD_CORTEX_A7_H
#define _BITFIELD_CORTEX_A7_H

#include "parse.h"

extern bitfield_info bitfield_cortex_a7_table[];
int return_bitfield_cortex_a7_size(void);

#define BO_A7_REVIDR_ID                 MSCODE(IMPL_CORTEX_A7, MS_IOCTL_REVIDR, FUNCTION_ID, 0)

#define BO_A7_MPIDR_CPUID               MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 0)
#define BO_A7_MPIDR_RESERVED_01         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 1)
#define BO_A7_MPIDR_CLUSTERID           MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 2)
#define BO_A7_MPIDR_RESERVED_02         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 3)
#define BO_A7_MPIDR_MT                  MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 4)
#define BO_A7_MPIDR_RESERVED_03         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 5)
#define BO_A7_MPIDR_U                   MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 6)
#define BO_A7_MPIDR_ME                  MSCODE(IMPL_CORTEX_A7, MS_IOCTL_MPIDR, FUNCTION_ID, 7)

#define BO_A7_ACTLR_RESERVED_01         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 0)
#define BO_A7_ACTLR_SMP                 MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 2)
#define BO_A7_ACTLR_RESERVED_02         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 3)
#define BO_A7_ACTLR_DODMBS              MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 4)
#define BO_A7_ACTLR_L2RADIS             MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 5)
#define BO_A7_ACTLR_L1RADIS             MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 6)   
#define BO_A7_ACTLR_L1PCTL              MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 7)
#define BO_A7_ACTLR_DDVM                MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 8)
#define BO_A7_ACTLR_RESERVED_03         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 9)
#define BO_A7_ACTLR_DDI                 MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 10)
#define BO_A7_ACTLR_RESERVED_04         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_ACTLR, FUNCTION_OTHER, 11)

#define BO_A7_NSACR_RESERVED_01         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 0)
#define BO_A7_NSACR_CP10                MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 1)
#define BO_A7_NSACR_CP11                MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 2)
#define BO_A7_NSACR_RESERVED_02         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 3)
#define BO_A7_NSACR_NSD32DIS            MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 4)      
#define BO_A7_NSACR_NSASEDIS            MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 5)
#define BO_A7_NSACR_RESERVED_03         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 6)
#define BO_A7_NSACR_NSL2ERR             MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 7)
#define BO_A7_NSACR_NSSMP               MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 8)
#define BO_A7_NSACR_RESERVED_04         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 9)
#define BO_A7_NSACR_RESERVED_05         MSCODE(IMPL_CORTEX_A7, MS_IOCTL_NSACR, FUNCTION_SECEXT, 10)

#define BO_A7_L2CTLR_LATENCY                MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2CTLR, FUNCTION_IMPLEMENTATION, 0)
#define BO_A7_L2CTLR_RESERVED_01            MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2CTLR, FUNCTION_IMPLEMENTATION, 1)
#define BO_A7_L2CTLR_IC                     MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2CTLR, FUNCTION_IMPLEMENTATION, 2)
#define BO_A7_L2CTLR_NUMPROC                MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2CTLR, FUNCTION_IMPLEMENTATION, 3)
#define BO_A7_L2CTLR_RESERVED_02            MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2CTLR, FUNCTION_IMPLEMENTATION, 4)

#define BO_A7_L2ECTLR_RESERVED_01           MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2ECTLR, FUNCTION_IMPLEMENTATION, 0)
#define BO_A7_L2ECTLR_AXI                   MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2ECTLR, FUNCTION_IMPLEMENTATION, 1)
#define BO_A7_L2ECTLR_RESERVED_02           MSCODE(IMPL_CORTEX_A7, MS_IOCTL_L2ECTLR, FUNCTION_IMPLEMENTATION, 2)

#define BO_A7_CBAR_PERIPHBASE_39_32     MSCODE(IMPL_CORTEX_A7, MS_IOCTL_CBAR, FUNCTION_IMPLEMENTATION, 0)
#define BO_A7_CBAR_RESERVED             MSCODE(IMPL_CORTEX_A7, MS_IOCTL_CBAR, FUNCTION_IMPLEMENTATION, 1)
#define BO_A7_CBAR_PERIPHBASE_31_15     MSCODE(IMPL_CORTEX_A7, MS_IOCTL_CBAR, FUNCTION_IMPLEMENTATION, 2)


#endif
