#include <stdio.h>
#include <sys/ioctl.h>

#include "maplesyrup.h"
#include "parse.h"
#include "bitfield_cortex-a57.h"

bitfield_info bitfield_cortex_a57_table[] =
{   
    { BO_A57_MPIDR_CPUID, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 0, 2, "CPU ID", "ident", "MPIDR", "Core number of Cortex-A57 processor" },
    { BO_A57_MPIDR_RESERVED_01, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 2, 6, "Reserved", "ident", "MPIDR", "Reserved" },
    { BO_A57_MPIDR_CLUSTERID1, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 8, 8, "Cluster ID Aff1", "ident", "MPIDR", "Affinity level 1" },
    { BO_A57_MPIDR_CLUSTERID2, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 16, 8, "Cluster ID Aff2", "ident", "MPIDR", "Affinity level 2" },
    { BO_A57_MPIDR_MT, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 24, 1, "MT", "ident", "MPIDR", "Lowest affinity cores are multi-threaded" },
    { BO_A57_MPIDR_RESERVED_02, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 25, 5, "Reserved", "ident", "MPIDR", "Reserved" },
    { BO_A57_MPIDR_U, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 30, 1, "U", "ident", "MPIDR", "Indicates a single core system" },
    { BO_A57_MPIDR_RESERVED_03, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 31, 1, "Reserved", "ident", "MPIDR", "Reserved" },
    { BO_A57_MPIDR_RESERVED_04, MS_IOCTL_MPIDR, NS_PRIVILEGE_LEVEL_1, 32, 32, "Reserved", "ident", "MPIDR", "Reserved" },  
    
    { BO_A57_SCTLR_EL1_M, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 0, 1, "M", "virtmem", "SCTLR", "MMU Enable" },
    { BO_A57_SCTLR_EL1_A, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 1, 1, "A", "virtmem", "SCTLR", "Alignment check enable" },
    { BO_A57_SCTLR_EL1_C, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 2, 1, "C", "virtmem", "SCTLR", "Cache enable" },
    { BO_A57_SCTLR_EL1_SA, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 3, 1, "SA", "virtmem", "SCTLR", "Stack alignment check enable" },
    { BO_A57_SCTLR_EL1_SA0, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 4, 1, "SA0", "virtmem", "SCTLR", "Stack alignment check enable for EL0" },
    { BO_A57_SCTLR_EL1_CP15BEN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "CP15BEN", "virtmem", "SCTLR", "CP15 barrier enable" },
    { BO_A57_SCTLR_EL1_THEE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "THEE", "virtmem", "SCTLR", "T32EE not implemented" },
    { BO_A57_SCTLR_EL1_ITD, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 7, 1, "ITD", "virtmem", "SCTLR", "Disables some uses of IT instructions at EL0 using AArch32" },
    { BO_A57_SCTLR_EL1_SED, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 8, 1, "SED", "virtmem", "SCTLR", "Disables the SETEND instruction at EL0 using AArch32" },
    { BO_A57_SCTLR_EL1_UMA, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 9, 1, "UMA", "virtmem", "SCTLR", "Traps EL0 execution of MSR and MRS instructions that access PSTATE" },
    { BO_A57_SCTLR_EL1_RESERVED_01, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 10, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_RESERVED_02, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 11, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_I, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 12, 1, "I", "virtmem", "SCTLR", "Instruction access Cacheability control" },
    { BO_A57_SCTLR_EL1_RESERVED_03, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 13, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_DZE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 14, 1, "DZE", "virtmem", "SCTLR", "Traps EL0 execution of DC ZVA instructions to EL1" },
    { BO_A57_SCTLR_EL1_UCT, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 15, 1, "UCT", "virtmem", "SCTLR", "Traps EL0 access to the CTR_EL0 register to EL1" },
    { BO_A57_SCTLR_EL1_NTWI, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 16, 1, "NTWI", "virtmem", "SCTLR", "Traps EL0 execution of WFI instructions to EL1" },
    { BO_A57_SCTLR_EL1_RESERVED_04, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 17, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_NTWE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 18, 1, "NTWE", "virtmem", "SCTLR", "Traps EL0 execution of WFE instructions to EL1" },
    { BO_A57_SCTLR_EL1_WXN, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 19, 1, "WXN", "virtmem", "SCTLR", "Write permission implies XN (Execute Never) at EL0/1" },
    { BO_A57_SCTLR_EL1_RESERVED_05, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 20, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_RESERVED_06, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_RESERVED_07, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 22, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_E0E, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "E0E", "virtmem", "SCTLR", "Endianess of data access at EL0" },
    { BO_A57_SCTLR_EL1_EE, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 25, 1, "EE", "virtmem", "SCTLR", "Endianess of data at EL1 and translation table walk" },
    { BO_A57_SCTLR_EL1_UCI, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 26, 1, "UCI", "virtmem", "SCTLR", "Traps EL0 cache maintenance instructions to EL1" },
    { BO_A57_SCTLR_EL1_RESERVED_08, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 27, 1, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_RESERVED_09, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 28, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    { BO_A57_SCTLR_EL1_RESERVED_10, MS_IOCTL_SCTLR, NS_PRIVILEGE_LEVEL_1, 30, 2, "Reserved", "virtmem", "SCTLR", "Reserved" },
    
    { BO_A57_TTBR0_RESERVED, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 0, 10, "Reserved", "virtmem", "TTBR0", "Reserved" },
    { BO_A57_TTBR0_BADDR, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 10, 38, "BADDR", "virtmem", "TTBR0", "Translation table base address" },
    { BO_A57_TTBR0_ASID, MS_IOCTL_TTBR0, NS_PRIVILEGE_LEVEL_1, 48, 16, "ASID", "virtmem", "TTBR0", "ASID for translation table base address" },
    
    { BO_A57_TTBR1_RESERVED, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 0, 10, "Reserved", "virtmem", "TTBR1", "Reserved" },
    { BO_A57_TTBR1_BADDR, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 10, 38, "BADDR", "virtmem", "TTBR1", "Translation table base address" },
    { BO_A57_TTBR1_ASID, MS_IOCTL_TTBR1, NS_PRIVILEGE_LEVEL_1, 48, 16, "ASID", "virtmem", "TTBR1", "ASID for translation table base address" },
    
    { BO_A57_ESR_IFSC, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 0, 6, "IFSC", "fault", "ESR", "Instruction Fault Status Code" },
    { BO_A57_ESR_RESERVED_01, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 6, 1, "Reserved", "fault", "ESR", "Reserved" },
    { BO_A57_ESR_S1TPW, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 7, 1, "S1PTW", "fault", "ESR", "Indicates instruction fault from translation table walk" },
    { BO_A57_ESR_RESERVED_02, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 8, 1, "Reserved", "fault", "ESR", "Reserved" },
    { BO_A57_ESR_EA, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 9, 1, "EA", "fault", "ESR", "External abort type" },
    { BO_A57_ESR_RESERVED_03, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 10, 15, "Reserved", "fault", "ESR", "Reserved" },
    { BO_A57_ESR_IL, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 25, 1, "IL", "fault", "ESR", "Instruction length for synchronous exceptions" },
    { BO_A57_ESR_EC, MS_IOCTL_DFSR, NS_PRIVILEGE_LEVEL_1, 26, 6, "EC", "fault", "ESR", "Exception class" },

    { BO_A57_PAR_F, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 0, 1, "D", "addrtrans", "PAR", "Indicates successful conversion" },
    { BO_A57_PAR_RESERVED_01, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 1, 6, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A57_PAR_SHA, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 7, 2, "SHA", "addrtrans", "PAR", "Shareability attribute" },
    { BO_A57_PAR_NS, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 9, 1, "NS", "addrtrans", "PAR", "Non-secure" },
    { BO_A57_PAR_RESERVED_02, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 10, 1, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A57_PAR_RESERVED_03, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 11, 1, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A57_PAR_PA, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 12, 36, "PA", "addrtrans", "PAR", "Physical address" },
    { BO_A57_PAR_RESERVED_04, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 48, 8, "Reserved", "addrtrans", "PAR", "Reserved" },
    { BO_A57_PAR_ATTRL, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 56, 4, "AttrL", "addrtrans", "PAR", "Defines device memory and inner cacheability" },
    { BO_A57_PAR_ATTRH, MS_IOCTL_PAR, NS_PRIVILEGE_LEVEL_1, 60, 4, "AttrH", "addrtrans", "PAR", "Defined normal and device memory and outer cacheability" },

    { BO_A57_L2CTLR_DATALATENCY, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 0, 3, "DATALATENCY", "impl_def", "L2CTLR", "L2 Data RAM latency" },
    { BO_A57_L2CTLR_RESERVED_01, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 3, 2, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A57_L2CTLR_DATASETUP, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "DATASETUP", "impl_def", "L2CTLR", "L2 Data RAM setup" },
    { BO_A57_L2CTLR_TAGLATENCY, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 6, 3, "L2 Tag RAM latency", "impl_def", "L2CTLR", "L2 Tag RAM latency" },
    { BO_A57_L2CTLR_TAGSETUP, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 9, 1, "TAGSETUP", "impl_def", "L2CTLR", "L2 Tag RAM setup" },
    { BO_A57_L2CTLR_DATASLICE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 10, 2, "DATASLICE", "impl_def", "L2CTLR", "L2 Data RAM slice" },
    { BO_A57_L2CTLR_TAGSLICE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 12, 1, "TAGSLICE", "impl_def", "L2CTLR", "L2 Tag RAM slice" },
    { BO_A57_L2CTLR_ARBSLICE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 13, 1, "ARBSLICE", "impl_def", "L2CTLR", "L2 arbitration slice" },
    { BO_A57_L2CTLR_RESERVED_02, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 14, 6, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A57_L2CTLR_DIECCE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 20, 1, "DIECCE", "impl_def", "L2CTLR", "Data inline ECC enable" },
    { BO_A57_L2CTLR_ECCPE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "ECCPE", "impl_def", "L2CTLR", "ECC and parity enable" },
    { BO_A57_L2CTLR_L1CPE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 22, 1, "L1CPE", "impl_def", "L2CTLR", "L1 cache ECC and parity protection" },
    { BO_A57_L2CTLR_RESERVED_03, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 23, 1, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A57_L2CTLR_NUMPROC, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 24, 2, "Number of processors", "impl_def", "L2CTLR", "Number of processors" },
    { BO_A57_L2CTLR_RESERVED_04, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 26, 5, "Reserved", "impl_def", "L2CTLR", "Reserved" },
    { BO_A57_L2CTLR_L2RSTDISABLE, MS_IOCTL_L2CTLR, NS_PRIVILEGE_LEVEL_1, 31, 1, "L2RSTDISABLE monitor", "impl_def", "L2CTLR", "Monitors the L2 hardware reset disable signal" },
    
    { BO_A57_L2ECTLR_DYNRET, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 0, 3, "DYNRET", "impl_def", "L2ECTLR", "L2 dynamic retention control" },
    { BO_A57_L2ECTLR_RESERVED_01, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 3, 26, "Reserved", "impl_def", "L2ECTLR", "Reserved" },
    { BO_A57_L2ECTLR_ASYNCERR, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 29, 1, "ASYNCERR", "impl_def", "L2ECTLR", "ACI or AMBA 5 CHI asynchronous error" },
    { BO_A57_L2ECTLR_IASYNCERR, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 30, 1, "IASYNCERR", "impl_def", "L2ECTLR", "L2 internal asynchronous error" },
    { BO_A57_L2ECTLR_RESERVED_02, MS_IOCTL_L2ECTLR, NS_PRIVILEGE_LEVEL_1, 31, 1, "IASYNCERR", "impl_def", "L2ECTLR", "L2 internal asynchronous error" },
    
    { BO_A57_L2ACTLR_DHPF, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 0, 1, "DHPF", "impl_def", "L2ACTLR", "Disable hardware prefetch foward" },
    { BO_A57_L2ACTLR_EARTT, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 1, 1, "EARTT", "impl_def", "L2ACTLR", "Enable arbitration replay threshold limit" },
    { BO_A57_L2ACTLR_LTORPTB, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 2, 1, "LTORPTB", "impl_def", "L2ACTLR", "Limit to one request per tag bank" },
    { BO_A57_L2ACTLR_DCEPTE, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 3, 1, "DCEPTE", "impl_def", "L2ACTLR", "Disable clean/evict push to external" },
    { BO_A57_L2ACTLR_DWWTFM, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 4, 1, "DWWTFM", "impl_def", "L2ACTLR", "Disable WriteUnique and WriteLineUnique transactions from master" },
    { BO_A57_L2ACTLR_RESERVED_01, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A57_L2ACTLR_DACE, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "DACE", "impl_def", "L2ACTLR", "Disable ACE shareable or CHI snoopable transactions from master" },
    { BO_A57_L2ACTLR_EHDT, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 7, 1, "EHDT", "impl_def", "L2ACTLR", "Enable hazard-detect timeout" },
    { BO_A57_L2ACTLR_DMB, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 8, 1, "DMB", "impl_def", "L2ACTLR", "Disable DVM/CMO message broadcast" },
    { BO_A57_L2ACTLR_RESERVED_02, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 9, 1, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A57_L2ACTLR_DNSDAA, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 10, 1, "DNSDAA", "impl_def", "L2ACTLR", "Disable Non-secure debug array access" },
    { BO_A57_L2ACTLR_DDSB, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 11, 1, "DDSB", "impl_def", "L2ACTLR", "Disable DSB with no DVM-sync" },
    { BO_A57_L2ACTLR_RESERVED_03, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 12, 1, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A57_L2ACTLR_DCEO, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 13, 1, "DCEO", "impl_def", "L2ACTLR", "Disable clean/evict optimization" },
    { BO_A57_L2ACTLR_EUED, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 14, 1, "EUED", "impl_def", "L2ACTLR", "Enable UniqueClean evictions with data" },
    { BO_A57_L2ACTLR_DFF, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 15, 1, "DFF", "impl_def", "L2ACTLR", "Disable fast fowarding of data from ACE or CHI to LS and IF" },
    { BO_A57_L2ACTLR_ERTSI, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 16, 1, "ERTSI", "impl_def", "L2ACTLR", "Enable replay threshold single issue" },
    { BO_A57_L2ACTLR_DL2RR, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 17, 1, "DL2RR", "impl_def", "L2ACTLR", "Disable L2 round-robin arbitration that only clocks through paths with an active requester waiting to be arbitrated" },
    { BO_A57_L2ACTLR_DLASQ, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 18, 2, "DLASQ", "impl_def", "L2ACTLR", "Disable limit on NC/SO/Dev stores in Address Sequence Queue" },
    { BO_A57_L2ACTLR_DTL2PR, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 20, 2, "DTL2PR", "impl_def", "L2ACTLR", "Disable throttling of L2 prefetch requests based on Fill/Evict Queue occupancy count" },
    { BO_A57_L2ACTLR_DDTPR, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 22, 1, "DDTPR", "impl_def", "L2ACTLR", "Disable dynamic throttling of LS prefetch requests" },
    { BO_A57_L2ACTLR_DPFR, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 23, 1, "DPFR", "impl_def", "L2ACTLR", "Disable PF requests from ReadUnique transactions" },
    { BO_A57_L2ACTLR_RESERVED_04, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "Reserved", "impl_def", "L2ACTLR", "Reserved" },
    { BO_A57_L2ACTLR_ESIAL, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 25, 1, "ESIAL", "impl_def", "L2ACTLR", "Enable single issue across all tag banks when L2 arbitration replay threshold is reached" },
    { BO_A57_L2ACTLR_FL2, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 26, 1, "FL2", "impl_def", "L2ACTLR", "Force L2, GIC, Timer RCG enables active" },
    { BO_A57_L2ACTLR_FL2LC, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 27, 1, "FL2LC", "impl_def", "L2ACTLR", "Force L2 logic clock enable active" }, 
    { BO_A57_L2ACTLR_FL2TB, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 28, 1, "FL2LC", "impl_def", "L2ACTLR", "Force L2 tag banks clock enable active" }, 
    { BO_A57_L2ACTLR_RESERVED_05, MS_IOCTL_L2ACTLR, NS_PRIVILEGE_LEVEL_1, 29, 3, "Reserved", "impl_def", "L2ACTLR", "Reserved" },  
    
    { BO_A57_CPUACTLR_BTB, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 0, 1, "BTB", "impl_def", "CPUACTLR", "Enables invalidates of BTB" },
    { BO_A57_CPUACTLR_DICMS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 1, 1, "DICMS", "impl_def", "CPUACTLR", "Disable instruction cache miss streaming" },
    { BO_A57_CPUACTLR_RESERVED_05, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 2, 1, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A57_CPUACTLR_DMBTB, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 3, 1, "DMBTB", "impl_def", "CPUACTLR", "Disables micro-Branch Target Buffer" },
    { BO_A57_CPUACTLR_DIP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 4, 1, "DIP", "impl_def", "CPUACTLR", "Disable interrupt predictor" },
    { BO_A57_CPUACTLR_EPLDNOP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 5, 1, "EPLDNOP", "impl_def", "CPUACTLR", "Execute PLD instruction as a NOP" },
    { BO_A57_CPUACTLR_RESERVED_06, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A57_CPUACTLR_EWFENOP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 7, 1, "EWFENOP", "impl_def", "CPUACTLR", "Executes WFE instruction as a NOP instruction" },
    { BO_A57_CPUACTLR_EWFINOP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 8, 1, "EWFINOP", "impl_def", "CPUACTLR", "Executes WFI instruction as a NOP instruction" },
    { BO_A57_CPUACTLR_DFRO, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 9, 1, "DFRO", "impl_def", "CPUACTLR", "Disable flag renaming optimization" },
    { BO_A57_CPUACTLR_FS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 10, 1, "FS", "impl_def", "CPUACTLR", "Force serialization after each instruction group" },
    { BO_A57_CPUACTLR_L1PIG, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 11, 1, "L1PIG", "impl_def", "CPUACTLR", "Limit to one instruction per instruction group" },
    { BO_A57_CPUACTLR_FPCP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 12, 1, "FPCP", "impl_def", "CPUACTLR", "Forces push of certain SPRs from local dispatch copies to shadow copies" },
    { BO_A57_CPUACTLR_FLCP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 13, 1, "FLCP", "impl_def", "CPUACTLR", "Flush after certain SPR writes" },
    { BO_A57_CPUACTLR_FL, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 14, 1, "FL", "impl_def", "CPUACTLR", "Force limit of one instruction group commit/deallocate per cycle" },
    { BO_A57_CPUACTLR_FIOBEU, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 15, 1, "FIOBEU", "impl_def", "CPUACTLR", "Force in-order issue in branch execution unit" },
    { BO_A57_CPUACTLR_EFSO, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 16, 1, "EFSO", "impl_def", "CPUACTLR", "Enable full strongly-ordered and device load replay" },
    { BO_A57_CPUACTLR_DL2_01, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 17, 1, "DL2_01", "impl_def", "CPUACTLR", "Disables L2 TLB performance optimizations" }, 
    { BO_A57_CPUACTLR_DL2_02, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 18, 1, "DL2_02", "impl_def", "CPUACTLR", "Disables L2 stage 1 translation table walk L2 PA cache" },
    { BO_A57_CPUACTLR_DL2_03, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 19, 1, "DL2_03", "impl_def", "CPUACTLR", "Disable L2 stage 1 translation table walk cache" },
    { BO_A57_CPUACTLR_DL2_04, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 20, 1, "DL2_04", "impl_def", "CPUACTLR", "Disable L2 translation table walk IPA PA cache" },
    { BO_A57_CPUACTLR_DL2_05, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 21, 1, "DL2_05", "impl_def", "CPUACTLR", "Disable L2 TLB prefetching" },
    { BO_A57_CPUACTLR_FIOL, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 22, 1, "FIOL", "impl_def", "CPUACTLR", "Force in-order load issue" }, 
    { BO_A57_CPUACTLR_FIOR, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 23, 1, "FIOR", "impl_def", "CPUACTLR", "Force in-order requests to the same set and way" },
    { BO_A57_CPUACTLR_NCSE, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 24, 1, "NCSE", "impl_def", "CPUACTLR", "Non-cacheable streaming enhancement" },
    { BO_A57_CPUACTLR_WSL1T, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 25, 2, "WSL1T", "impl_def", "CPUACTLR", "Write streaming no L1-allocate threshold" },
    { BO_A57_CPUACTLR_WSNAT, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 27, 2, "WSNAT", "impl_def", "CPUACTLR", "Write streaming no allocate threshold" },
    { BO_A57_CPUACTLR_FNCEA, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 29, 1, "FNCEA", "impl_def", "CPUACTLR", "Force Advanced SIMD and Floating-point clock enable active" },
    { BO_A57_CPUACTLR_FMCEA, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 30, 1, "FMCEA", "impl_def", "CPUACTLR", "Force main clock enable active" },
    { BO_A57_CPUACTLR_SDEH, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 31, 1, "SDEH", "impl_def", "CPUACTLR", "Snoop-delayed exclusive handling" },      
    { BO_A57_CPUACTLR_DICP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 32, 1, "DICP", "impl_def", "CPUACTLR", "Disable instruction cache prefetch" },
    { BO_A57_CPUACTLR_DICW, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 33, 1, "DICW", "impl_def", "CPUACTLR", "Disable instruction Cache way" },
    { BO_A57_CPUACTLR_DSBP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 34, 1, "DSBP", "impl_def", "CPUACTLR", "Disable static branch predictor" },
    { BO_A57_CPUACTLR_RESERVED_01, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 35, 1, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A57_CPUACTLR_FIDSB, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 36, 1, "FIDSB", "impl_def", "CPUACTLR", "Force implicit DSB on an ISB" },
    { BO_A57_CPUACTLR_DIGS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 37, 1, "DIGS", "impl_def", "CPUACTLR", "Disable instruction group split" },
    { BO_A57_CPUACTLR_FFWF, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 38, 1, "FFWF", "impl_def", "CPUACTLR", "Force FPSCR write flush" },
    { BO_A57_CPUACTLR_DIM, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 39, 1, "DIM", "impl_def", "CPUACTLR", "Disable instruction merging" },
    { BO_A57_CPUACTLR_RESERVED_02, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 40, 4, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A57_CPUACTLR_EDC, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 44, 1, "EDC", "impl_def", "CPUACTLR", "Execute Data Cache clean as Data Cache clean/invalidate" },
    { BO_A57_CPUACTLR_RESERVED_03, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 45, 2, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A57_CPUACTLR_DDSIDE, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 47, 1, "DDSIDE", "impl_def", "CPUACTLR", "Disable D-side L1/L2 hardware prefetch across 4KB page boundary even if page is 64KB or larger" },
    { BO_A57_CPUACTLR_DESRA, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 48, 1, "DESRA", "impl_def", "CPUACTLR", "Disable early speculative read access from LS to L2" },
    { BO_A57_CPUACTLR_DNAH, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 49, 1, "DNAH", "impl_def", "CPUACTLR", "Disable non-allocate hint of Write-Back No-Allocate memory type" },
    { BO_A57_CPUACTLR_DSS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 50, 1, "DSS", "impl_def", "CPUACTLR", "Disable store streaming on NC/GRE memory type" },
    { BO_A57_CPUACTLR_DCD, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 51, 1, "DCD", "impl_def", "CPUACTLR", "Disable contention detection and fast exclusive monitor path" },
    { BO_A57_CPUACTLR_DOR, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 52, 1, "DOR", "impl_def", "CPUACTLR", "Disable over-read from LDNP instruction" },
    { BO_A57_CPUACTLR_TDMB, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 53, 1, "TDMB", "impl_def", "CPUACTLR", "Treat DMB/DSB as if their domain field is SY" },
    { BO_A57_CPUACTLR_TGRE, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 54, 1, "TGRE", "impl_def", "CPUACTLR", "Tread GRE/nGRE as nGnRE" },
    { BO_A57_CPUACTLR_DLPS, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 55, 1, "DLPS", "impl_def", "CPUACTLR", "Disable load pass store" },
    { BO_A57_CPUACTLR_DL1HP, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 56, 1, "DL1HP", "impl_def", "CPUACTLR", "Disable L1 hardware prefetcher" },
    { BO_A57_CPUACTLR_TDMBA, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 57, 1, "TDMBA", "impl_def", "CPUACTLR", "Treat DMB st/st and ld/all as DMB all/all" },
    { BO_A57_CPUACTLR_DDMBN, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 58, 1, "DDMBN", "impl_def", "CPUACTLR", "Disable DMB nullification" },
    { BO_A57_CPUACTLR_DLPDMB, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 59, 1, "DLPDMB", "impl_def", "CPUACTLR", "Disable load pass DMB" },
    { BO_A57_CPUACTLR_RESERVED_04, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 60, 3, "Reserved", "impl_def", "CPUACTLR", "Reserved" },
    { BO_A57_CPUACTLR_FPRCG, MS_IOCTL_CPUACTLR, NS_PRIVILEGE_LEVEL_1, 63, 1, "FPRCG", "impl_def", "CPUACTLR", "Force processor RCG enables active" },

    { BO_A57_CPUMERRSR_INDEX, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 0, 18, "RAMADDR", "impl_def", "CPUMERRSR", "Indicates the index address of the first memory error" },  
    { BO_A57_CPUMERRSR_BANKWAY, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 18, 5, "CPUIDWAY", "impl_def", "CPUMERRSR", "Indicates the RAM where the first memory error occurred" }, 
    { BO_A57_CPUMERRSR_RESERVED_01, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 23, 1, "Reserved", "impl_def", "CPUMERRSR", "Reserved" },    
    { BO_A57_CPUMERRSR_RAMID, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 24, 7, "RAMID", "impl_def", "CPUMERRSR", "Ram Identifier" },
    { BO_A57_CPUMERRSR_VALID, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 31, 1, "Valid", "impl_def", "CPUMERRSR", "Valid bit. Set to 1 on first memory error" },
    { BO_A57_CPUMERRSR_REC, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 32, 8, "REC", "impl_def", "CPUMERRSR", "Repeat memory error count when valid bit is set" },
    { BO_A57_CPUMERRSR_OEC, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 40, 8, "OEC", "impl_def", "CPUMERRSR", "Other memory error count when valid bit is set" },
    { BO_A57_CPUMERRSR_RESERVED_02, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 48, 15, "Reserved", "impl_def", "CPUMERRSR", "Reserved" },
    { BO_A57_CPUMERRSR_FATAL, MS_IOCTL_CPUMERRSR, NS_PRIVILEGE_LEVEL_1, 63, 1, "Fatal", "impl_def", "CPUMERRSR", "Fatal bit. Set to 1 on first memory error that cased data abort" },

    { BO_A57_L2MERRSR_INDEX, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 0, 18, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A57_L2MERRSR_CPUIDWAY, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 18, 4, "CPUIDWAY", "impl_def", "L2MERRSR", "Indicates the RAM where the first memory error occurred" },   
    { BO_A57_L2MERRSR_RESERVED_01, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 22, 2, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A57_L2MERRSR_RAMID, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 24, 7, "RAMID", "impl_def", "L2MERRSR", "Indicates the RAM where the first memory error occurred" }, 
    { BO_A57_L2MERRSR_VALID, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 31, 1, "VALID", "impl_def", "L2MERRSR", "Valid bit. Set to 1 on first memory error" },
    { BO_A57_L2MERRSR_REC, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 32, 8, "REC", "impl_def", "L2MERRSR", "Repeat memory error count when valid bit is set" },
    { BO_A57_L2MERRSR_OEC, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 40, 8, "OEC", "impl_def", "L2MERRSR", "Other memory error count when valid bit is set" },
    { BO_A57_L2MERRSR_RESERVED_02, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 48, 15, "Reserved", "impl_def", "L2MERRSR", "Reserved" },
    { BO_A57_L2MERRSR_FATAL, MS_IOCTL_L2MERRSR, NS_PRIVILEGE_LEVEL_1, 63, 1, "Fatal", "impl_def", "L2MERRSR", "Fatal bit. Set to 1 on first memory error that cased data abort" },

    { BO_A57_CBAR_RESERVED_01, MS_IOCTL_CBAR, NS_PRIVILEGE_LEVEL_1, 0, 18, "Reserved", "impl_def", "CBAR", "Reserved" },
    { BO_A57_CBAR_PERIPHBASE, MS_IOCTL_CBAR, NS_PRIVILEGE_LEVEL_1, 18, 32, "PERIPHBASE", "impl_def", "CBAR", "Reset base address of memory-mapped GIC CPU interface registers" },
    { BO_A57_CBAR_RESERVED_02, MS_IOCTL_CBAR, NS_PRIVILEGE_LEVEL_1, 40, 24, "Reserved", "impl_def", "CBAR", "Reserved" },

    { BO_A57_CPUECTLR_PDRC, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 0, 3, "PDRC", "impl_def", "CPUECTLR", "Process dynamic retention control" },
    { BO_A57_CPUECTLR_RESERVED_01, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 3, 3, "Reserved", "impl_def", "CPUECTLR", "Reserved" },
    { BO_A57_CPUECTLR_SMPEN, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 6, 1, "SMPEN", "impl_def", "CPUECTLR", "Enable processor to receive instruction cache and TLB maintenance operations broadcast from other processors in the cluster" },
    { BO_A57_CPUECTLR_RESERVED_02, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 7, 25, "Reserved", "impl_def", "CPUECTLR", "Reserved" },
    { BO_A57_CPUECTLR_L2IFPD, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 32, 2, "L2IFPD", "impl_def", "CPUECTLR", "Indicates the L2 load/store data prefetch distance" },
    { BO_A57_CPUECTLR_RESERVED_03, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 34, 1, "Reserved", "impl_def", "CPUECTLR", "Reserved" },
    { BO_A57_CPUECTLR_L2LSDPD, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 35, 2, "L2LSDPD", "impl_def", "CPUECTLR", "Indicates the L2 instruction fetch prefetch distance" },
    { BO_A57_CPUECTLR_RESERVED_04, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 37, 1, "Reserved", "impl_def", "CPUECTLR", "Reserved" },
    { BO_A57_CPUECTLR_DTWDAP, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 38, 1, "DTWDAP", "impl_def", "CPUECTLR", "Disable table walk descriptor access prefetch" },
    { BO_A57_CPUECTLR_RESERVED_05, MS_IOCTL_CPUECTLR, NS_PRIVILEGE_LEVEL_1, 39, 25, "Reserved", "impl_def", "CPUECTLR", "Reserved" },

};

int
return_bitfield_cortex_a57_size(void)
{
    return (sizeof(bitfield_cortex_a57_table) / sizeof(bitfield_info));
}
