#ifdef __KERNEL__
    #include <linux/module.h>
    #include <linux/ioctl.h>    
#else
    #include <stdio.h>
    #include <sys/ioctl.h>  
#endif

#include "cmd_handler.h"

#include "cp15.h"
#include "vfpu.h"
#include "psr.h"
#include "aarch64.h"

func_table_entry func_table[] =
{   
    /* ID Handlers */
    { MS_IOCTL_MIDR, do_MIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CTR, do_CTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_TCMTR, do_TCMTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_TLBTR, do_TLBTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MPIDR, do_MPIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_REVIDR, do_REVIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_AFR0, do_AFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MMFR0, do_MMFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_MMFR1, do_MMFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MMFR2, do_MMFR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MMFR3, do_MMFR3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_PFR0, do_PFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PFR1, do_PFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ISAR0, do_ISAR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ISAR1, do_ISAR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ISAR2, do_ISAR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ISAR3, do_ISAR3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ISAR4, do_ISAR4_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ISAR5, do_ISAR5_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CLIDR, do_CLIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_AIDR, do_AIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CSSELR, do_CSSELR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DFR0, do_DFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CCSIDR, do_CCSIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 }, 
    
    /* Virtual Memory Handlers */
    { MS_IOCTL_SCTLR, do_SCTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PRRR, do_PRRR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MAIR, do_MAIR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_MAIR0, do_MAIR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MAIR1, do_MAIR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_NMRR, do_NMRR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_TTBCR, do_TTBCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },    
    { MS_IOCTL_TTBR0, do_TTBR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_TTBR0LPAE, do_TTBR0LPAE_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_32 },
    { MS_IOCTL_TTBR1, do_TTBR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_TTBR1LPAE, do_TTBR1LPAE_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CONTEXTIDR, do_CONTEXTIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_AMAIR0, do_AMAIR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_AMAIR1, do_AMAIR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_AMAIR, do_AMAIR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_DACR, do_DACR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DCZID, do_DCZID_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    
    /* Fault Handling Handlers */
    { MS_IOCTL_IFAR, do_IFAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_IFSR, do_IFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ADFSR, do_ADFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_AIFSR, do_AIFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DFAR, do_DFAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DFSR, do_DFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 }, 
    { MS_IOCTL_FAR, do_FAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },   
    
    /* Performance Monitor Handlers */
    { MS_IOCTL_PMCCFILTR, do_PMCCFILTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMCR, do_PMCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMCCNTR, do_PMCCNTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_PMCEID0, do_PMCEID0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMCEID1, do_PMCEID1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMCNTENCLR, do_PMCNTENCLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMCNTENSET, do_PMCNTENSET_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 }, 
    { MS_IOCTL_PMINTENCLR, do_PMINTENCLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMINTENSET, do_PMINTENSET_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMOVSR, do_PMOVSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMOVSCLR, do_PMOVSCLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMOVSSET, do_PMOVSSET_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMSELR, do_PMSELR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMSWINC, do_PMSWINC_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMUSERENR, do_PMUSERENR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMXEVCNTR, do_PMXEVCNTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_PMXEVTYPER, do_PMXEVTYPER_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    
    /* Security Extension Handlers */       
    { MS_IOCTL_VBAR, do_VBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_ISR, do_ISR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_MVBAR, do_MVBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_NSACR, do_NSACR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_SCR, do_SCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_SDER, do_SDER_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 }, 
    
    /* "Other" Handlers */  
    { MS_IOCTL_CPACR, do_CPACR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_FCSEIDR, do_FCSEIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_RMR, do_RMR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_RVBAR, do_RVBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    
    /* Address Translation Handlers */  
    { MS_IOCTL_PAR, do_PAR_read, FUNCTYPE_OUT_1 , FUNCTYPE_BITS_ARCH },
    
    /* Floating Point Handlers */
    { MS_IOCTL_FPEXC, do_FPEXC_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },       
    { MS_IOCTL_FPSCR, do_FPSCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_FPSID, do_FPSID_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_MVFR0, do_MVFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_MVFR1, do_MVFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_MVFR2, do_MVFR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
        
    /* Debug Handlers */
    { MS_IOCTL_DBGDIDR, do_DBGDIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DBGAUTHSTATUS, do_DBGAUTHSTATUS_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DBGDRAR, do_DBGDRAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_DBGDSCR, do_DBGDSCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    
    /* Misc */
    { MS_IOCTL_TPIDRPRW, do_TPIDRPRW_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_TPIDRURO, do_TPIDRURO_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_TPIDRURW, do_TPIDRURW_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    
    /* Jazelle */
    { MS_IOCTL_JIDR, do_JIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },     
    { MS_IOCTL_JMCR, do_JMCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_JOSCR, do_JOSCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },       
    
    /* Thumb */
    { MS_IOCTL_TEECR, do_TEECR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_TEEHBR, do_TEEHBR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    
    /* Implementation Defined */
    { MS_IOCTL_CPUMERRSR, do_CPUMERRSR_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_L2MERRSR, do_L2MERRSR_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_ARCH },
    { MS_IOCTL_L2ACTLR, do_L2ACTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ACTLR, do_ACTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_ACTLR2, do_ACTLR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CPUACTLR, do_CPUACTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_L2PFR, do_L2PFR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_L2CTLR, do_L2CTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_L2ECTLR, do_L2ECTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },   
    { MS_IOCTL_CPUECTLR, do_CPUECTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_IL1DATA0, do_IL1DATA0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_IL1DATA1, do_IL1DATA1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_IL1DATA2, do_IL1DATA2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_IL1DATA3, do_IL1DATA3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DL1DATA0, do_DL1DATA0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DL1DATA1, do_DL1DATA1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DL1DATA2, do_DL1DATA2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DL1DATA3, do_DL1DATA3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CBAR, do_CBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
        
    /* AARCH64 */   
    { MS_IOCTL_AA64AFR0, do_AA64AFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64AFR1, do_AA64AFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64DFR0, do_AA64DFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64DFR1, do_AA64DFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64ISAR0, do_AA64ISAR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64ISAR1, do_AA64ISAR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64MMFR0, do_AA64MMFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64MMFR1, do_AA64MMFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64PFR0, do_AA64PFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_IOCTL_AA64PFR1, do_AA64PFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    
    /* Special purpose registers */
    { MS_IOCTL_CURRENTEL, do_CURRENTEL_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_DAIF, do_DAIF_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_FPCR, do_FPCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_FPSR, do_FPSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_NZCV, do_NZCV_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_SPSEL, do_SPSEL_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    
    /* Program Status Register */
    { MS_IOCTL_APSR, do_APSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_CPSR, do_CPSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_IOCTL_SPSR, do_SPSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    
        
    { 0, NULL, 0 , 0},  
};

int
return_table_size(void)
{
    return sizeof(func_table) / sizeof(func_table_entry);
}
